import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface Translations {
  [key: string]: {
    en: string;
    zh: string;
  };
}

const translations: Translations = {
  // Navigation
  'nav.home': { en: 'Home', zh: '首页' },
  'nav.buy': { en: 'Buy', zh: '买房' },
  'nav.rent': { en: 'Rent', zh: '租房' },
  'nav.blog': { en: 'Blog', zh: '博客' },
  'nav.about': { en: 'About', zh: '关于我们' },
  'nav.consultation': { en: 'Free Consultation', zh: '免费咨询' },
  'nav.account': { en: 'My Account', zh: '我的账户' },
  'nav.signin': { en: 'Sign In', zh: '登录' },
  
  // Hero Section
  'hero.title.1': { en: 'Your Gateway to', zh: '' },
  'hero.title.2': { en: 'Japanese Real Estate', zh: '在东京拥有您的理想资产' },
  'hero.subtitle': { en: 'Buy and Live in Japan with Confidence', zh: '海外人士安心购房，日本置业更简单' },
  'hero.btn.consultation': { en: 'Book Free Consultation', zh: '预约免费咨询' },
  'hero.btn.social': { en: 'Contact Us on Social Media', zh: '通过社交媒体咨询' },
  
  // Quick Search
  'search.title': { en: 'Find Your Perfect Property in Tokyo', zh: '寻找您的理想之家' },
  'search.buy': { en: 'Buy', zh: '买房' },
  'search.rent': { en: 'Rent', zh: '租房' },
  'search.area.label': { en: 'Area', zh: '区域' },
  'search.area.placeholder': { en: 'Select Area', zh: '请选择区域' },
  'search.type.label': { en: 'Property Type', zh: '物业类型' },
  'search.type.placeholder': { en: 'Select Type', zh: '请选择类型' },
  'search.price.label': { en: 'Price Range', zh: '价格范围' },
  'search.price.placeholder': { en: 'Any Price', zh: '不限价格' },
  'search.btn': { en: 'Search Properties', zh: '搜索房源' },
  'search.btn_short': { en: 'Search', zh: '搜索' },
  'search.placeholder.keyword': { en: 'Search by title, address, station...', zh: '按标题、地址、车站搜索...' },
  'search.area.select': { en: 'Select area', zh: '选择区域' },
  'search.area.one': { en: '1 area', zh: '1 个区域' },
  'search.area.many': { en: '{n} areas', zh: '{n} 个区域' },
  'search.area.search_placeholder': { en: 'Search area...', zh: '搜索区域...' },
  'search.budget.any': { en: 'Any', zh: '不限' },
  'search.budget.any_budget': { en: 'Any budget', zh: '不限预算' },
  'search.budget.price': { en: 'Price', zh: '价格' },
  'search.budget.monthly_rent': { en: 'Monthly Rent', zh: '月租' },
  'search.bedrooms.label': { en: 'Bedrooms', zh: '户型' },
  'search.bedrooms.studio': { en: 'Studio', zh: '单身公寓' },
  'search.bedrooms.1br': { en: '1 BR', zh: '1室' },
  'search.bedrooms.2br': { en: '2 BR', zh: '2室' },
  'search.bedrooms.3br': { en: '3 BR', zh: '3室' },
  'search.bedrooms.4br_plus': { en: '4 BR+', zh: '4室以上' },
  'search.budget.under_50m': { en: 'Under ¥50M', zh: '5000万日元以下' },
  'search.budget.50m_80m': { en: '¥50M – ¥80M', zh: '5000万–8000万日元' },
  'search.budget.80m_120m': { en: '¥80M – ¥120M', zh: '8000万–1.2亿日元' },
  'search.budget.120m_200m': { en: '¥120M – ¥200M', zh: '1.2亿–2亿日元' },
  'search.budget.over_200m': { en: 'Over ¥200M', zh: '2亿日元以上' },
  'search.budget.under_150k': { en: 'Under ¥150,000', zh: '15万日元以下/月' },
  'search.budget.150k_250k': { en: '¥150,000 – ¥250,000', zh: '15万–25万日元/月' },
  'search.budget.250k_400k': { en: '¥250,000 – ¥400,000', zh: '25万–40万日元/月' },
  'search.budget.400k_600k': { en: '¥400,000 – ¥600,000', zh: '40万–60万日元/月' },
  'search.budget.over_600k': { en: 'Over ¥600,000', zh: '60万日元以上/月' },
  'search.size.label': { en: 'Property Size (m²)', zh: '面积 (m²)' },
  'search.size.from': { en: 'From', zh: '最小' },
  'search.size.to': { en: 'To', zh: '最大' },
  'search.size.placeholder_min': { en: 'e.g. 30', zh: '例如 30' },
  'search.size.placeholder_max': { en: 'e.g. 80', zh: '例如 80' },
  'search.area.header': { en: 'Tokyo 23 wards + Outer 23 wards', zh: '东京23区 + 23区外' },
  'search.area.no_match': { en: 'No matching area', zh: '无匹配区域' },
  'search.area.label_short': { en: 'Area', zh: '区域' },

  // Tokyo ward names (23 wards + Outer 23 + outer cities for Tokyo Wards section)
  'ward.Chiyoda': { en: 'Chiyoda', zh: '千代田区' },
  'ward.Chuo': { en: 'Chuo', zh: '中央区' },
  'ward.Minato': { en: 'Minato', zh: '港区' },
  'ward.Shinjuku': { en: 'Shinjuku', zh: '新宿区' },
  'ward.Bunkyo': { en: 'Bunkyo', zh: '文京区' },
  'ward.Taito': { en: 'Taito', zh: '台東区' },
  'ward.Sumida': { en: 'Sumida', zh: '墨田区' },
  'ward.Koto': { en: 'Koto', zh: '江東区' },
  'ward.Shinagawa': { en: 'Shinagawa', zh: '品川区' },
  'ward.Meguro': { en: 'Meguro', zh: '目黒区' },
  'ward.Ota': { en: 'Ota', zh: '大田区' },
  'ward.Setagaya': { en: 'Setagaya', zh: '世田谷区' },
  'ward.Shibuya': { en: 'Shibuya', zh: '渋谷区' },
  'ward.Nakano': { en: 'Nakano', zh: '中野区' },
  'ward.Suginami': { en: 'Suginami', zh: '杉並区' },
  'ward.Toshima': { en: 'Toshima', zh: '豊島区' },
  'ward.Kita': { en: 'Kita', zh: '北区' },
  'ward.Arakawa': { en: 'Arakawa', zh: '荒川区' },
  'ward.Itabashi': { en: 'Itabashi', zh: '板橋区' },
  'ward.Nerima': { en: 'Nerima', zh: '練馬区' },
  'ward.Adachi': { en: 'Adachi', zh: '足立区' },
  'ward.Katsushika': { en: 'Katsushika', zh: '葛飾区' },
  'ward.Edogawa': { en: 'Edogawa', zh: '江戸川区' },
  'ward.Outside23': { en: 'Outer 23 wards', zh: '23区外' },
  'ward.Hachioji': { en: 'Hachioji', zh: '八王子市' },
  'ward.Tachikawa': { en: 'Tachikawa', zh: '立川市' },
  'ward.Musashino': { en: 'Musashino', zh: '武蔵野市' },
  'ward.Mitaka': { en: 'Mitaka', zh: '三鷹市' },
  'ward.Ome': { en: 'Ome', zh: '青梅市' },
  'ward.Fuchu': { en: 'Fuchu', zh: '府中市' },
  'ward.Akishima': { en: 'Akishima', zh: '昭島市' },
  'ward.Chofu': { en: 'Chofu', zh: '調布市' },
  'ward.Machida': { en: 'Machida', zh: '町田市' },
  'ward.Koganei': { en: 'Koganei', zh: '小金井市' },
  'ward.Kodaira': { en: 'Kodaira', zh: '小平市' },
  'ward.Hino': { en: 'Hino', zh: '日野市' },
  'ward.Higashimurayama': { en: 'Higashimurayama', zh: '東村山市' },
  'ward.Kokubunji': { en: 'Kokubunji', zh: '国分寺市' },
  'ward.Kunitachi': { en: 'Kunitachi', zh: '国立市' },
  'ward.Fussa': { en: 'Fussa', zh: '福生市' },
  'ward.Komae': { en: 'Komae', zh: '狛江市' },
  'ward.Higashiyamato': { en: 'Higashiyamato', zh: '東大和市' },
  'ward.Kiyose': { en: 'Kiyose', zh: '清瀬市' },
  'ward.Higashikurume': { en: 'Higashikurume', zh: '東久留米市' },
  'ward.Musashimurayama': { en: 'Musashimurayama', zh: '武蔵村山市' },
  'ward.Tama': { en: 'Tama', zh: '多摩市' },
  'ward.Inagi': { en: 'Inagi', zh: '稲城市' },
  'ward.Hamura': { en: 'Hamura', zh: '羽村市' },
  'ward.Akiruno': { en: 'Akiruno', zh: 'あきる野市' },
  'ward.Nishitokyo': { en: 'Nishitokyo', zh: '西東京市' },

  // Sections
  'section.featured.title': { en: 'Featured Properties', zh: '精选房源' },
  'section.featured.subtitle': { en: 'Handpicked premium properties in top locations', zh: '为您精选的核心地段优质房源' },
  'section.areas.title': { en: 'Popular Areas', zh: '热门区域' },
  'section.areas.subtitle': { en: 'Explore the most sought-after neighborhoods in Tokyo', zh: '探索东京最受欢迎的居住区' },
  'section.areas.explore_title': { en: 'Explore Tokyo Wards', zh: '探索东京各区' },
  'section.areas.explore_desc': { en: 'Discover popular areas across Tokyo, from central business districts to quiet residential neighborhoods.', zh: '从繁华商圈到宜居社区，探索东京人气区域。' },
  'section.areas.wards23': { en: '23 Special Wards', zh: '东京23区' },
  'section.areas.outer': { en: 'Outer 23 Wards', zh: '23区外' },
  'section.areas.view_rentals': { en: 'View Rentals', zh: '查看出租' },
  'section.areas.view_sale': { en: 'View for Sale', zh: '查看出售' },
  'section.areas.show_more': { en: 'Show more', zh: '显示更多' },
  'section.areas.show_less': { en: 'Show less', zh: '收起' },
  'section.areas.properties_count': { en: '{n} properties', zh: '{n} 个房源' },
  'section.featured.view_all': { en: 'View all', zh: '查看全部' },
  'section.featured.view_all_properties': { en: 'View all properties', zh: '查看全部房源' },
  'section.featured.loading': { en: 'Loading...', zh: '加载中...' },
  'section.featured.empty': { en: 'No featured properties', zh: '暂无精选房源' },
  'section.featured.swipe': { en: 'Swipe', zh: '滑动' },
  'section.categories.title': { en: 'Search by Categories', zh: '按类别搜索' },
  'section.categories.properties_count': { en: '{n} Properties', zh: '{n} 个房源' },
  'category.pet_friendly': { en: 'Pet friendly', zh: '允许养宠物' },
  'search.advanced_filters': { en: 'Advanced filters', zh: '高级筛选' },
  'section.why.title': { en: 'Why Tokyo Expat Housing', zh: '为什么选择我们' },
  'section.why.subtitle': { en: 'Your trusted partner in Japanese real estate', zh: '您值得信赖的日本置业伙伴' },

  // Why Us
  'why.support.title': { en: 'Multilingual Support', zh: '多语言服务' },
  'why.support.desc': { en: 'Full support in English and Chinese throughout your entire journey.', zh: '提供全程中英文无障碍沟通服务。' },
  'why.process.title': { en: 'Transparent Process', zh: '流程透明' },
  'why.process.desc': { en: 'Clear explanations of all costs, contracts, and legal requirements.', zh: '清晰讲解所有费用、合同及法律要求。' },
  'why.network.title': { en: 'Extensive Network', zh: '海量房源' },
  'why.network.desc': { en: 'Access to exclusive off-market properties across Tokyo.', zh: '独家渠道，获取东京未公开的优质房源。' },

  // Trust Section
  'trust.brokerage.title': { en: 'Licensed & Compliant Brokerage', zh: '正规持牌中介' },
  'trust.brokerage.desc': { en: 'Officially registered under Japanese real estate law with full regulatory compliance and transparent transaction management.', zh: '严格遵守日本房地产法律正式注册，合规经营，交易管理透明。' },
  'trust.multilingual.title': { en: 'Multilingual Professional Support', zh: '多语言专业支持' },
  'trust.multilingual.desc': { en: 'Dedicated multilingual team providing contract explanation, negotiation, and full transaction assistance.', zh: '专业多语言团队，提供合同讲解、价格谈判及全程交易协助。' },
  'trust.specialist.title': { en: 'Foreign Resident Specialists', zh: '外籍人士置业专家' },
  'trust.specialist.desc': { en: 'Extensive experience assisting expats and non-Japanese residents with rentals and purchases.', zh: '在协助外籍人士和非日籍居民租房、买房方面拥有丰富经验。' },

  // Process Section
  'process.title': { en: 'Our Process', zh: '服务流程' },
  'process.step1.title': { en: 'Initial Consultation', zh: '初步咨询' },
  'process.step1.desc': { en: 'Contact us via email, LINE, WeChat, Whatsapp, Instagram, or the inquiry form. Share your goals (rent or purchase), budget, preferred area, timeline, and any special requirements.', zh: '通过邮件、LINE、微信、Whatsapp、Instagram 或咨询表单联系我们。分享您的目标（租房或买房）、预算、意向区域、时间表及任何特殊要求。' },
  'process.step2.title': { en: 'Property Proposal', zh: '房源提案' },
  'process.step2.desc': { en: 'Based on your needs, we carefully select suitable properties and provide:', zh: '根据您的需求，我们精选合适的房源并提供：' },
  'process.step2.list1': { en: 'Photos & floor plans', zh: '照片与户型图' },
  'process.step2.list2': { en: 'Pricing details', zh: '价格详情' },
  'process.step2.list3': { en: 'Estimated initial costs', zh: '预估初期费用' },
  'process.step2.list4': { en: 'Key property information', zh: '关键房源信息' },
  'process.step3.title': { en: 'Viewing & Application', zh: '看房与申请' },
  'process.step3.desc': { en: 'We arrange property viewings (in-person or virtual). Once you find your ideal home, we guide you through the application process and negotiate terms on your behalf.', zh: '我们安排看房（实地或视频）。一旦您找到理想的房子，我们将指导您完成申请流程并代表您进行条款谈判。' },
  'process.step4.title': { en: 'Contract & Handover', zh: '合同与交房' },
  'process.step4.desc': { en: 'We explain all contract details clearly in your preferred language. After signing, we coordinate the payment schedule and key handover for a smooth move-in experience.', zh: '我们用您熟悉的语言清晰地讲解所有合同细节。签约后，我们协调付款时间表和钥匙交接，确保您顺利入住。' },
  'process.step3.heading': { en: 'Viewing (In-Person or Online)', zh: '看房（实地或线上）' },
  'process.step3.desc_long': { en: 'You may visit the property in person or join an online viewing via Zoom. We explain the property condition, neighborhood, and relevant considerations.', zh: '您可实地看房或通过 Zoom 参加线上看房。我们会说明房屋状况、周边环境及注意事项。' },
  'process.step4.heading': { en: 'Application or Purchase Offer', zh: '申请或购房要约' },
  'process.step4.desc_rent': { en: 'For Rentals: We assist with the rental application and required documentation.', zh: '租房：我们协助您完成租赁申请及所需材料。' },
  'process.step4.desc_buy': { en: 'For Purchases: We help prepare and submit a formal purchase offer.', zh: '买房：我们协助准备并提交正式购房要约。' },
  'process.step5.heading': { en: 'Screening or Negotiation', zh: '审核或议价' },
  'process.step5.desc_rent': { en: 'Rentals: Landlord screening (2–5 business days).', zh: '租房：房东审核（约 2–5 个工作日）。' },
  'process.step5.desc_buy': { en: 'Purchases: Price negotiation and agreement on terms.', zh: '买房：价格协商及条款确认。' },
  'process.step6.heading': { en: 'Contract Preparation & Explanation', zh: '合同准备与说明' },
  'process.step6.desc': { en: 'We prepare the contract documents and clearly explain all terms and conditions in English before signing.', zh: '我们准备合同文件，并在签约前用英语清晰说明全部条款。' },
  'process.step7.heading': { en: 'Payment & Final Procedures', zh: '付款与最终手续' },
  'process.step7.desc_rent': { en: 'Rentals: Initial move-in costs (deposit, key money, agency fee, etc.)', zh: '租房：入住初期费用（押金、礼金、中介费等）' },
  'process.step7.desc_buy': { en: 'Purchases: Deposit payment and remaining balance settlement', zh: '买房：定金支付及尾款结算' },
  'process.step7.guide': { en: 'We guide you through every payment step.', zh: '我们全程协助您完成各项付款。' },
  'process.step8.heading': { en: 'Key Handover', zh: '钥匙交接' },
  'process.step8.desc': { en: 'Once procedures are completed, you receive the keys and officially take possession of your new home.', zh: '手续完成后，您将领取钥匙并正式入住新居。' },
  'why.section.title': { en: 'Why Tokyo Expat Housing', zh: '为什么选择 Tokyo Expat Housing' },
  'why.multilingual.title': { en: 'Multilingual Professional Support (EN / JP / CN / KR)', zh: '多语言专业支持（英 / 日 / 中 / 韩）' },
  'why.multilingual.desc': { en: 'Full support in four languages, ensuring accurate communication from property search to contract signing. No misunderstandings — just clear guidance tailored for international clients.', zh: '提供英日中韩四语全程支持，从找房到签约沟通无误。为国际客户提供清晰、贴心的指导。' },
  'why.approval.title': { en: 'Strong Approval Expertise for Foreign Clients', zh: '外籍客户审核通过率高' },
  'why.approval.desc': { en: 'We understand which properties and guarantor companies are more foreigner-friendly. Our structured approach helps maximize rental approval success and smooth transactions.', zh: '我们熟悉哪些房源与担保公司对外籍人士更友好，通过系统化流程提高租房通过率，让交易更顺畅。' },
  'why.fast.title': { en: 'Fast, Transparent & Structured Process', zh: '高效、透明、流程清晰' },
  'why.fast.desc': { en: 'We work with clear timelines and proactive coordination to meet your move-in goals. Every step — from pricing to paperwork — is explained clearly so you can move forward with confidence.', zh: '我们按明确时间表主动协调，助您顺利入住。从价格到文书，每一步都清晰说明，让您安心推进。' },
  'cta.title': { en: 'Ready to Start Your Journey?', zh: '准备好开始了吗？' },
  'cta.desc': { en: "Schedule a free consultation with our expert team. We'll guide you through every step of finding your perfect property in Japan.", zh: '预约我们的专家团队免费咨询。我们将全程协助您在日本找到理想房源。' },
  'cta.book': { en: 'Book Free Consultation', zh: '预约免费咨询' },
  'cta.browse': { en: 'Browse Properties', zh: '浏览房源' },
  'footer.follow': { en: 'Follow Us', zh: '关注我们' },
  'footer.social.open': { en: 'Open', zh: '打开' },
  'footer.mailto.subject': { en: 'Inquiry', zh: '咨询' },
  'footer.mailto.body': { en: 'Hello,\n\n', zh: '您好，\n\n' },
  'about.mailto.subject': { en: 'Inquiry', zh: '咨询' },
  'about.mailto.body': { en: 'Hello, I would like to inquire about...', zh: '您好，我想咨询...' },
  'property.loading': { en: 'Loading...', zh: '加载中...' },
  'property.favorite.add_aria': { en: 'Add to favorites', zh: '添加到收藏' },
  'property.favorite.remove_aria': { en: 'Remove from favorites', zh: '从收藏中移除' },
  'property.tour.signin_required': { en: 'Please sign in to your account to request a room tour.', zh: '请先登录账户以预约看房。' },
  'property.tour.submit_error': { en: 'Failed to submit. Please try again.', zh: '提交失败，请重试。' },
  'property.tour.time_range': { en: 'Time range', zh: '时间段' },
  'property.tour.option_n': { en: 'Option {n}', zh: '选项 {n}' },
  'listing.title.rent': { en: 'Properties for rent', zh: '出租房源' },
  'listing.title.rent.ward': { en: 'Properties for rent in {ward}', zh: '{ward} 的出租房源' },
  'listing.results_count': { en: '{count} results', zh: '{count} 个结果' },
  'listing.monthly_rent_label': { en: 'Monthly Rent:', zh: '月租金：' },
  'activity.details_requested': { en: 'Details requested', zh: '已索取详情' },
  'activity.room_tour_booked': { en: 'Room tour booked', zh: '已预约看房' },
  'activity.for_rent': { en: 'For Rent', zh: '出租' },
  'activity.for_sale': { en: 'For Sale', zh: '出售' },
  'listing.properties_found': { en: '{count} properties found', zh: '共 {count} 个房源' },
  'account.favorites': { en: 'Favorites', zh: '收藏夹' },
  'account.activity': { en: 'Activity', zh: '我的动态' },
  'account.profile': { en: 'Profile', zh: '个人资料' },
  'account.logout': { en: 'Logout', zh: '退出登录' },
  'account.user': { en: 'User', zh: '用户' },
  'favorites.title': { en: 'Favorites', zh: '收藏夹' },
  'favorites.no_favorites': { en: 'No favorites yet.', zh: '暂无收藏。' },
  'favorites.no_match_rent': { en: '0 rental properties match the filters.', zh: '没有符合筛选条件的出租房源。' },
  'favorites.no_match_buy': { en: '0 properties for sale match the filters.', zh: '没有符合筛选条件的出售房源。' },
  'activity.title': { en: 'Applied Properties', zh: '已申请房源' },
  'activity.subtitle': { en: 'View properties for which you have requested a room tour or property details.', zh: '查看您已预约看房或索取详情的房源。' },
  'activity.preferred_tour_dates': { en: 'Preferred tour dates', zh: '首选看房日期' },
  'activity.no_rent': { en: 'No rental properties with tour or inquiry requests.', zh: '暂无已预约看房或索取详情的出租房源。' },
  'activity.no_buy': { en: 'No properties for sale with tour or inquiry requests.', zh: '暂无已预约看房或索取详情的出售房源。' },

  'profile.title': { en: 'Profile', zh: '个人资料' },
  'profile.tab_information': { en: 'Information', zh: '基本信息' },
  'profile.tab_password': { en: 'Password', zh: '密码' },
  'profile.first_name': { en: 'First name', zh: '名' },
  'profile.last_name': { en: 'Last name', zh: '姓' },
  'profile.email_address': { en: 'Email address', zh: '邮箱地址' },
  'profile.saved_success': { en: 'Saved successfully.', zh: '保存成功。' },
  'profile.saved_error': { en: 'Failed to save. Please try again.', zh: '保存失败，请重试。' },
  'profile.saving': { en: 'Saving...', zh: '保存中...' },
  'profile.save': { en: 'Save', zh: '保存' },
  'profile.current_password': { en: 'Current password', zh: '当前密码' },
  'profile.new_password': { en: 'New password', zh: '新密码' },
  'profile.password_placeholder': { en: 'At least 8 characters', zh: '至少8个字符' },
  'profile.confirm_password': { en: 'Confirm new password', zh: '确认新密码' },
  'profile.password_success': { en: 'Password updated successfully.', zh: '密码更新成功。' },
  'profile.password_error': { en: 'Failed to update. Check current password or use at least 8 characters.', zh: '更新失败。请检查当前密码或使用至少8个字符。' },
  'profile.updating': { en: 'Updating...', zh: '更新中...' },
  'profile.update_password': { en: 'Update password', zh: '更新密码' },

          // Property Detail
          'property.back': { en: 'Back', zh: '返回' },
          'property.photo': { en: 'Photo', zh: '照片' },
          'property.brochure': { en: 'Brochure', zh: '宣传册' },
          'property.favorite.added': { en: 'Added to Favorites.', zh: '已添加到收藏夹。' },
          'property.favorite.removed': { en: 'Removed from Favorites.', zh: '已从收藏夹移除。' },
          'property.favorite.error': { en: 'Could not save. Please try again.', zh: '无法保存，请重试。' },
          'property.initial_fees_card': { en: 'Initial fees can be paid by credit card', zh: '初期费用可使用信用卡支付' },
          'property.initial_fees_card_note': { en: '*Additional transaction fees may apply', zh: '*可能收取额外的交易手续费' },
  'property.tour.title': { en: 'Request a Tour', zh: '预约看房' },
  'property.tour.request_room_tour': { en: 'Request a room tour', zh: '预约看房' },
  'property.tour.date1': { en: 'Candidate Date 1', zh: '候选日期 1' },
  'property.tour.date2': { en: 'Candidate Date 2', zh: '候选日期 2' },
  'property.tour.date3': { en: 'Candidate Date 3', zh: '候选日期 3' },
  'property.tour.name': { en: 'Name', zh: '姓名' },
  'property.tour.email': { en: 'Email', zh: '邮箱' },
  'property.tour.submit': { en: 'Request Tour', zh: '提交预约' },
  'property.tour.success': { en: 'Tour requested successfully. We will contact you soon.', zh: '看房预约成功。我们将尽快与您联系。' },
  'property.tour.preferred_times_error': { en: 'Failed to save preferred times.', zh: '首选时间保存失败，请重试。' },
  'property.tour.confirm': { en: 'Confirm', zh: '确认' },
  'property.back_to_list': { en: 'Back to list', zh: '返回列表' },
  'property.inquiry.title': { en: 'Inquire About This Property', zh: '咨询此房源' },
  'property.inquiry.name': { en: 'Name', zh: '姓名' },
  'property.inquiry.email': { en: 'Email', zh: '邮箱' },
  'property.inquiry.message': { en: 'Message (optional)', zh: '留言（选填）' },
  'property.inquiry.submit': { en: 'Send Inquiry', zh: '发送咨询' },
  'property.inquiry.success': { en: 'Inquiry sent successfully.', zh: '咨询发送成功。' },
  'property.overview': { en: 'Overview', zh: '概览' },
  'property.description': { en: 'Property Description', zh: '房源描述' },
  'property.location': { en: 'Location', zh: '位置' },
  'property.features': { en: 'Features & Amenities', zh: '设施与配套' },
  'property.readMore': { en: 'Read More', zh: '阅读更多' },
  'property.showLess': { en: 'Show Less', zh: '收起' },
  'property.information': { en: 'Property Information', zh: '房源信息' },
  'property.type': { en: 'Type', zh: '类型' },
  'property.layout': { en: 'Layout', zh: '户型' },
  'property.size': { en: 'Size', zh: '面积' },
  'property.built': { en: 'Built', zh: '竣工年份' },
          'property.floor': { en: 'Floor', zh: '楼层' },
          'property.station': { en: 'Station', zh: '车站' },
          'property.notfound': { en: 'Property not found', zh: '未找到房源' },
          'error.fetch_failed': { en: 'Unable to load. Please check your connection and try again.', zh: '无法加载。请检查网络后重试。' },
          'common.retry': { en: 'Retry', zh: '重试' },
          'property.price.rent': { en: 'Monthly rent', zh: '月租金' },
          'property.price.buy': { en: 'Price', zh: '售价' },
          'property.feature.pet': { en: 'Pet-friendly', zh: '允许养宠物' },
          'property.feature.foreign': { en: 'Foreign-friendly', zh: '外籍友好' },
          'property.feature.balcony': { en: 'Balcony', zh: '阳台' },
          'property.feature.bicycle': { en: 'Bicycle parking', zh: '自行车停放处' },
          'property.feature.delivery': { en: 'Delivery box', zh: '快递箱' },
          'property.feature.elevator': { en: 'Elevator', zh: '电梯' },
          'property.feature.south': { en: 'South facing', zh: '朝南' },
          'property.tour.instruction': { en: 'Please provide up to 3 preferred date and time options. We will contact you to confirm.', zh: '请提供最多3个首选日期和时间选项。我们将与您联系以确认。' },
          'property.tour.option': { en: 'Option', zh: '选项' },
          'property.tour.date': { en: 'Date', zh: '日期' },
          'property.tour.time': { en: 'Time', zh: '时间' },
          'property.tour.time.any': { en: 'Any time', zh: '任何时间' },
          'property.tour.time.morning': { en: 'Morning', zh: '上午' },
          'property.tour.time.afternoon': { en: 'Afternoon', zh: '下午' },
          'property.tour.time.evening': { en: 'Evening', zh: '晚上' },
          'property.placeholder.name': { en: 'Your Name', zh: '您的姓名' },
          'property.placeholder.email': { en: 'your@email.com', zh: '您的电子邮箱' },
          'property.placeholder.message': { en: 'Any questions about this property?', zh: '关于此房源有任何疑问吗？' },
          'property.sending': { en: 'Sending...', zh: '发送中...' },
          'property.walk.min': { en: 'min walk', zh: '分钟步行' },
          'property.walk.min_short': { en: 'min', zh: '分钟' },
          'property.check_availability.title': { en: 'Check Availability and Request Property Details', zh: '查看可预约时间并索取房源详情' },
          'property.check_availability.btn': { en: 'Check availability', zh: '查看空房' },
          'property.check_availability.desc': { en: 'Enter your name and email address. We will send you availability and full details for this property. You can check anytime.', zh: '请输入您的姓名和电子邮箱。我们将向您发送该房源的可预约时间及详细资料，您可随时查看。' },
          'property.check_availability.name': { en: 'Name', zh: '姓名' },
          'property.check_availability.email': { en: 'Email address', zh: '电子邮箱' },
          'property.check_availability.success': { en: 'Property details request already submitted. A staff member will contact you within 24 hours.', zh: '房源详情已提交。工作人员将在24小时内与您联系。' },
          'property.bed': { en: 'bed', zh: '室' },
          'property.bath': { en: 'bath', zh: '卫' },
          'property.management_fee': { en: 'Management fee', zh: '管理费' },
          'property.deposit': { en: 'Deposit', zh: '押金' },
          'property.no_deposit': { en: 'No deposit', zh: '无押金' },
          'property.key_money': { en: 'Key money', zh: '礼金' },
          'property.no_key_money': { en: 'No key money', zh: '无礼金' },
          'property.bedrooms': { en: 'Bedrooms', zh: '卧室数量' },
          'property.rental_fees': { en: 'Rental fees', zh: '租赁费用' },

          // Listing & Filters
          'filter.title': { en: 'Filters', zh: '筛选' },
          'filter.show_map': { en: 'Show map', zh: '显示地图' },
          'map.loading': { en: 'Loading map...', zh: '地图加载中...' },
          'map.no_address': { en: 'No address provided.', zh: '未提供地址。' },
          'map.geocode_error': { en: 'Could not get location from address.', zh: '无法根据地址获取位置。' },
          'map.cannot_display': { en: 'Cannot display map.', zh: '无法显示地图。' },
          'map.property_location': { en: 'Property location', zh: '房源位置' },
          'map.cluster_count': { en: '{n} properties', zh: '{n} 个房源' },
          'map.click_to_zoom': { en: 'Click to zoom in', zh: '点击放大' },
          'map.view_details_new_tab': { en: 'View details (new tab)', zh: '查看详情（新标签页）' },
          'map.bed': { en: 'bed', zh: '室' },
          'map.no_properties': { en: 'No properties to show on map.', zh: '地图上暂无房源。' },
          'map.view_details': { en: 'View details', zh: '查看详情' },
          'filter.hide': { en: 'Hide', zh: '隐藏' },
          'filter.show': { en: 'Show', zh: '显示' },
          'filter.search': { en: 'Search', zh: '搜索' },
          'filter.property_type': { en: 'Property Type', zh: '房源类型' },
          'filter.type.apartment': { en: 'Apartment', zh: '公寓' },
          'filter.type.condominium': { en: 'Condominium', zh: '高级公寓' },
          'filter.type.house': { en: 'House', zh: '独栋别墅' },
          'filter.type.studio': { en: 'Studio', zh: '单身公寓' },
          'filter.station': { en: 'Station', zh: '车站' },
          'filter.selected_area': { en: 'Selected Area', zh: '选择区域' },
          'filter.price': { en: 'Price', zh: '价格' },
          'filter.price_range': { en: 'Price range', zh: '价格范围' },
          'filter.no_min': { en: 'No min', zh: '不限下限' },
          'filter.no_max': { en: 'No max', zh: '不限上限' },
          'filter.size': { en: 'Size (m²)', zh: '面积 (m²)' },
          'filter.bedrooms': { en: 'Bedrooms', zh: '户型' },
          'filter.bedrooms.any': { en: 'Any', zh: '不限' },
          'filter.all': { en: 'All', zh: '全部' },
          'filter.listing_type': { en: 'Listing Type:', zh: '类型：' },
          'filter.keyword_placeholder': { en: 'Keyword...', zh: '关键词...' },
          'filter.min_yen': { en: 'Min ¥', zh: '最低 ¥' },
          'filter.max_yen': { en: 'Max ¥', zh: '最高 ¥' },
          'filter.min_sqm': { en: 'Min m²', zh: '最小 m²' },
          'filter.max_sqm': { en: 'Max m²', zh: '最大 m²' },
          'filter.station_placeholder': { en: 'Station...', zh: '车站...' },
          'filter.more_filters': { en: 'More filters', zh: '更多筛选' },
          'filter.categories': { en: 'Categories', zh: '类别' },
          'filter.save': { en: 'Save', zh: '保存' },
          
          'category.luxury': { en: 'Luxury', zh: '豪华' },
          'category.furnished': { en: 'Furnished', zh: '带家具' },
          'category.high_rise': { en: 'High-Rise Residence', zh: '高层住宅' },
          'category.no_key_money': { en: 'No key money', zh: '无礼金' },
          'category.students': { en: 'For students', zh: '适合学生' },
          'category.designers': { en: 'Designers', zh: '设计师公寓' },
          'category.families': { en: 'For families', zh: '适合家庭' },
          'category.foreign_friendly': { en: 'Foreign friendly', zh: '外国人友好' },

          'sort.popularity': { en: 'Popularity', zh: '热门程度' },
          'sort.price_asc': { en: 'Price (Low to High)', zh: '价格 (从低到高)' },
          'sort.price_desc': { en: 'Price (High to Low)', zh: '价格 (从高到低)' },
          'sort.size_asc': { en: 'Size (Small to Large)', zh: '面积 (从小到大)' },
          'sort.size_desc': { en: 'Size (Large to Small)', zh: '面积 (从大到小)' },
          'sort.walking_asc': { en: 'Walking (Near to Far)', zh: '步行 (从近到远)' },
          'sort.walking_desc': { en: 'Walking (Far to Near)', zh: '步行 (从远到近)' },
          'sort.newest': { en: 'Newest', zh: '最新' },
          'sort.oldest': { en: 'Oldest', zh: '最早' },
          'sort.label': { en: 'Sort by', zh: '排序' },
          'listing.title': { en: 'Properties for sale', zh: '出售房源' },
          'listing.title.ward': { en: 'Properties for sale in {ward}', zh: '{ward}的出售房源' },
          'listing.results': { en: '{count} results', zh: '{count} 个结果' },
          'listing.loading': { en: 'Loading...', zh: '加载中...' },
          'listing.error': { en: 'Error: {error}', zh: '错误: {error}' },
          'listing.empty': { en: 'No properties found.', zh: '未找到房源。' },
          'listing.badge.popular': { en: 'POPULAR', zh: '热门' },
          'listing.badge.new': { en: 'New', zh: '新上' },

          'listing.load_more': { en: 'Load more', zh: '加载更多' },

          // Consultation
          'consult.title': { en: 'Free Consultation', zh: '免费咨询' },
          'consult.desc': { en: "Tell us about your goals. We'll get back to you within 24 hours to schedule a call or meeting.", zh: '告诉我们您的目标。我们将在 24 小时内与您联系，安排电话或会议。' },
          'consult.thank_you': { en: 'Thank you', zh: '谢谢' },
          'consult.success_desc': { en: "We've received your request. Our team will contact you within 24 hours.", zh: '我们已收到您的请求。我们的团队将在 24 小时内与您联系。' },
          'consult.back_home': { en: 'Back to Home', zh: '返回首页' },
          'consult.name': { en: 'Name *', zh: '姓名 *' },
          'consult.name_ph': { en: 'Your name', zh: '您的姓名' },
          'consult.email': { en: 'Email *', zh: '邮箱 *' },
          'consult.email_ph': { en: 'you@example.com', zh: 'you@example.com' },
          'consult.phone': { en: 'Phone', zh: '电话' },
          'consult.phone_ph': { en: 'Phone number', zh: '电话号码' },
          'consult.search_country': { en: 'Search country...', zh: '搜索国家...' },
          'consult.interest': { en: 'I am interested in...', zh: '我感兴趣的是...' },
          'consult.interest_rent': { en: 'Renting a property', zh: '租房' },
          'consult.interest_buy': { en: 'Buying a property', zh: '买房' },
          'consult.date': { en: 'Preferred Date & Time', zh: '期望日期与时间' },
          'consult.online': { en: 'I prefer an online meeting (Zoom/Google Meet)', zh: '我倾向于线上会议 (Zoom/Google Meet 等)' },
          'consult.message': { en: 'How can we help you?', zh: '我们能为您提供什么帮助？' },
          'consult.message_ph': { en: 'Please share your budget, preferred areas, and any specific requirements...', zh: '请分享您的预算、意向区域以及任何特殊要求...' },
          'consult.submit': { en: 'Request Consultation', zh: '提交咨询' },

          // About Us
          'about.title': { en: 'About Us', zh: '关于我们' },
          'about.p1': { en: 'Tokyo Expat Housing (operated by Jokyo Property Co., Ltd.) is a Tokyo-based real estate service dedicated to international residents, students, and global clients.', zh: 'Tokyo Expat Housing（由上京プロパティ株式会社运营）是一家总部位于东京的房地产服务机构，致力于为国际居民、留学生及全球客户提供服务。' },
          'about.p2': { en: 'We specialize in helping international clients find ideal properties in Tokyo through clear communication, transparent fees, and full multilingual support.', zh: '我们专注于通过清晰的沟通、透明的收费标准和全面的多语言支持，帮助国际客户在东京找到理想的房产。' },
          'about.p3': { en: 'Our team brings diverse international experience, with backgrounds connected to the United States, China, and Korea. This global perspective enables us to understand cultural expectations, communication styles, and the unique challenges clients may face when relocating to Japan.', zh: '我们的团队拥有丰富的国际经验，具备与美国、中国和韩国相关的背景。这种全球视野使我们能够深入理解客户的文化期望、沟通方式，以及在移居日本时可能面临的独特挑战。' },
          'about.p4': { en: "Navigating Japan's housing system can be complex — from guarantor requirements to detailed contract procedures. Our role is to simplify the process and provide accurate, straightforward guidance at every step.", zh: '日本的住房系统可能相当复杂——从保证人要求到繁琐的合同程序。我们的职责是简化这一过程，并在每一步为您提供准确、直接的指导。' },
          'about.company_profile': { en: 'Company Profile', zh: '公司简介' },
          'about.company_name': { en: 'Company Name', zh: '公司名称' },
          'about.company_name_val': { en: 'Jokyo Property Co., Ltd.', zh: '上京プロパティ株式会社' },
          'about.license': { en: 'License', zh: '营业执照' },
          'about.license_val': { en: 'Tokyo Governor License (1) No. 113518', zh: '东京都知事执照 (1) 第113518号' },
          'about.corporate_number': { en: 'Corporate Number', zh: '法人编号' },
          'about.director': { en: 'Representative Director', zh: '代表取缔役' },
          'about.director_val': { en: 'Kosei Kudo', zh: 'Kosei Kudo' },
          'about.address': { en: 'Address', zh: '地址' },
          'about.address_val': { en: '77 Space 102, 3-1-5 Kita-Otsuka, Toshima-ku, Tokyo 170-0004, Japan', zh: '日本东京都丰岛区北大塚3-1-5 77Space 102 (邮编: 170-0004)' },
          'about.phone': { en: 'Phone', zh: '电话' },
          'about.email': { en: 'Email', zh: '电子邮箱' },

          // Blog
          'blog.title': { en: 'Blog', zh: '博客' },
          'blog.all': { en: 'All', zh: '全部' },
          'blog.loading': { en: 'Loading posts...', zh: '正在加载文章...' },
          'blog.error': { en: 'Error', zh: '错误' },
          'blog.error_desc': { en: 'Failed to load posts.', zh: '加载文章失败。' },
          'blog.not_found': { en: 'Post not found.', zh: '未找到文章。' },
          'blog.back_to_list': { en: 'Back to Blog List', zh: '返回博客列表' },
          'blog.preparing': { en: 'Preparing', zh: '准备中' },

          // Footer
  'footer.about': { en: 'Tokyo Expat Housing provides comprehensive real estate services for international clients, specializing in premium properties across Tokyo.', zh: 'Tokyo Expat Housing 致力于为全球客户提供全面的房地产服务，专注于东京的优质房产。' },
  'footer.quickLinks': { en: 'Quick Links', zh: '快捷链接' },
  'footer.contact': { en: 'Contact', zh: '联系我们' },
  'footer.address': { en: 'Tokyo, Japan', zh: '日本 东京' },
  'footer.rights': { en: '© 2026 Tokyo Expat Housing. All rights reserved.', zh: '© 2026 Tokyo Expat Housing. 保留所有权利。' },
  'footer.operated_by': { en: 'Operated by Jokyo Property Co., Ltd.', zh: '运营方：上京プロパティ株式会社' },
  'footer.license': { en: 'Tokyo Governor License (1) No. 113518', zh: '东京都知事执照 (1) 第113518号' },
  'footer.address_line1': { en: '77 Space 102, 3-1-5 Kita-Otsuka', zh: '东京都丰岛区北大塚3-1-5 77Space 102' },
  'footer.address_line2': { en: 'Toshima-ku, Tokyo 170-0004, Japan', zh: '〒170-0004 日本' },
  'footer.services': { en: 'Services', zh: '服务' },
  'footer.buy_property': { en: 'Buy Property', zh: '买房' },
  'footer.rent_live': { en: 'Rent & Live', zh: '租房' },
  'footer.company': { en: 'Company', zh: '公司' },
  'footer.copyright': { en: '© 2026 TK LLC. All Rights Reserved.', zh: '© 2026 TK LLC. 保留所有权利。' },
  'footer.privacy_policy': { en: 'Privacy Policy', zh: '隐私政策' },
  'footer.terms_of_service': { en: 'Terms of Service', zh: '服务条款' },
  'footer.cookie_policy': { en: 'Cookie Policy', zh: 'Cookie 政策' },

  // Cookie Policy
  'cookie.title': { en: 'Cookie Policy', zh: 'Cookie 政策' },
  'cookie.last_updated': { en: 'Last Updated: March 4th, 2026', zh: '最后更新：2026年3月4日' },
  'cookie.intro1': { en: 'Jokyo Property Co., Ltd. ("we," "us," or "our") uses cookies and similar tracking technologies on our website (the "Service") to distinguish you from other users of our Service. This helps us to provide you with a good experience when you browse our website, allows us to improve our site, and enables us to show you relevant content and advertisements.', zh: '上京プロパティ株式会社（「当社」「私たち」）は、当社ウェブサイト（「サービス」）において、他の利用者とお客様を区別するためにCookieおよび類似のトラッキング技術を使用しています。これにより、ウェブサイトの閲覧体験の向上、サイトの改善、および関連コンテンツ・広告の表示が可能になります。' },
  'cookie.intro2': { en: 'This Cookie Policy explains what cookies are, how we use them, the types of cookies we use, your choices regarding cookies, and further information about cookies. This policy complies with applicable laws in Japan, including the Act on the Protection of Personal Information (APPI).', zh: '本Cookie政策では、Cookieとは何か、当社の使用方法、使用するCookieの種類、お客様の選択肢、およびCookieに関する詳細について説明します。本政策は、個人情報の保護に関する法律（APPI）を含む日本国内の適用法令に準拠しています。' },
  'cookie.s1_title': { en: '1. What Are Cookies', zh: '1. Cookieとは' },
  'cookie.s1_p1': { en: 'Cookies are small text files that are placed on your computer, mobile device, or tablet when you visit a website. They are widely used by website owners to make their websites work, or to work more efficiently, as well as to provide reporting information.', zh: 'Cookieは、ウェブサイトにアクセスした際に、お客様のコンピュータ、モバイル端末、またはタブレットに保存される小さなテキストファイルです。ウェブサイトの動作や効率化、およびレポート情報の提供のために、サイト運営者によって広く利用されています。' },
  'cookie.s1_p2': { en: 'Cookies set by the website owner (in this case, Jokyo Property Co., Ltd.) are called "first-party cookies." Cookies set by parties other than the website owner are called "third-party cookies." Third-party cookies enable third-party features or functionality to be provided on or through the website (e.g., advertising, interactive content, and analytics).', zh: 'ウェブサイト運営者（ここでは上京プロパティ株式会社）が設定するCookieは「ファーストパーティCookie」、それ以外が設定するCookieは「サードパーティCookie」と呼ばれます。サードパーティCookieにより、広告・インタラクティブコンテンツ・分析など、第三者による機能がサイト上で提供されます。' },
  'cookie.s2_title': { en: '2. How We Use Cookies', zh: '2. Cookieの使用方法' },
  'cookie.s2_p1': { en: 'We use cookies for a variety of reasons detailed below. Unfortunately, in most cases, there are no industry standard options for disabling cookies without completely disabling the functionality and features they add to this site. It is recommended that you leave on all cookies if you are not sure whether you need them or not in case they are used to provide a service that you use.', zh: '当社は、以下に詳述する様々な目的でCookieを使用しています。多くの場合、Cookieが提供する機能を維持したまま無効にする業界標準の方法はありません。必要かどうか不明な場合は、利用中のサービスにCookieが使われている可能性があるため、すべてのCookieを有効のままにしておくことを推奨します。' },
  'cookie.s2_specifically': { en: 'Specifically, we use cookies to:', zh: '具体的には、当社はCookieを次の目的で使用します：' },
  'cookie.s2_li1': { en: 'Ensure the website functions correctly.', zh: 'ウェブサイトが正しく動作するようにする。' },
  'cookie.s2_li2': { en: 'Understand how you use our website to improve our services.', zh: '当社ウェブサイトの利用状況を把握し、サービスを改善する。' },
  'cookie.s2_li3': { en: 'Remember your preferences and settings (such as language or search criteria).', zh: '言語や検索条件などの設定・嗜好を記憶する。' },
  'cookie.s2_li4': { en: 'Deliver advertisements that are relevant to your interests.', zh: 'お客様の興味に合った広告を配信する。' },
  'cookie.s3_title': { en: '3. Types of Cookies We Use', zh: '3. 使用するCookieの種類' },
  'cookie.s3_h1': { en: 'Strictly Necessary Cookies', zh: '严格必要Cookie' },
  'cookie.s3_p1': { en: 'These cookies are essential for you to browse the website and use its features, such as accessing secure areas of the site. Without these cookies, services you have asked for cannot be provided. We do not require your consent to use these cookies as they are necessary for the operation of the website.', zh: 'これらのCookieは、サイトの閲覧や安全な領域へのアクセスなどの機能に不可欠です。これらがないと、ご要望いただいたサービスを提供できません。サイト運営に必要なため、同意なく使用します。' },
  'cookie.s3_h2': { en: 'Analytics and Performance Cookies', zh: 'Analytics and Performance Cookies（分析・パフォーマンスCookie）' },
  'cookie.s3_p2': { en: 'These cookies collect information about how you use our website, such as which pages you visit most often and if you receive error messages from web pages. These cookies do not collect information that identifies you as an individual; all information these cookies collect is aggregated and therefore anonymous. It is only used to improve how a website works.', zh: 'これらのCookieは、最も閲覧したページやエラーメッセージの有無など、当社ウェブサイトの利用方法に関する情報を収集します。個人を特定する情報は収集せず、集約された匿名データのみを使用し、サイトの改善に役立てます。' },
  'cookie.s3_h3': { en: 'Advertising and Targeting Cookies', zh: 'Advertising and Targeting Cookies（広告・ターゲティングCookie）' },
  'cookie.s3_p3': { en: "These cookies are used to deliver advertisements more relevant to you and your interests. They are also used to limit the number of times you see an advertisement as well as help measure the effectiveness of the advertising campaign. They are usually placed by advertising networks with the website operator's permission. They remember that you have visited a website and this information is shared with other organizations such as advertisers.", zh: 'これらのCookieは、お客様の興味に合った広告の配信、広告表示回数の制限、広告効果の測定に使用されます。通常、サイト運営者の許可を得た広告ネットワークが設置し、サイト訪問の記録を広告主などと共有することがあります。' },
  'cookie.s4_title': { en: '4. Third-Party Cookies', zh: '4. サードパーティCookie' },
  'cookie.s4_p1': { en: 'In addition to our own cookies, we may also use various third-parties cookies to report usage statistics of the Service, deliver advertisements on and through the Service, and so on.', zh: '当社のCookieに加え、サービスの利用統計の報告や、サービス上・経由での広告配信などのため、各種サードパーティのCookieを使用することがあります。' },
  'cookie.s4_ga': { en: 'Google Analytics', zh: 'Google Analytics' },
  'cookie.s4_ga_p1': { en: 'We use Google Analytics to help us understand how our customers use the site. Google Analytics uses cookies to collect information such as how often users visit this site, what pages they visit when they do so, and what other sites they used prior to coming to this site. We use the information we get from Google Analytics only to improve this site.', zh: '当社は、お客様のサイト利用状況を把握するためにGoogle Analyticsを使用しています。Google AnalyticsはCookieにより、訪問頻度、閲覧ページ、流入元サイトなどの情報を収集します。当社はこの情報をサイト改善の目的でのみ使用します。' },
  'cookie.s4_ga_link': { en: "For more information on how Google uses your data, please visit Google's Privacy & Terms.", zh: 'Googleによるデータの取扱いについては、Googleのプライバシーと利用規約をご覧ください。' },
  'cookie.s4_partners': { en: 'Advertising Partners', zh: '広告パートナー' },
  'cookie.s4_partners_p': { en: 'We work with third-party advertising companies to serve ads when you visit our website. These companies may use information (not including your name, address, email address, or telephone number) about your visits to this and other websites in order to provide advertisements about goods and services of interest to you.', zh: '当社は、お客様が当社ウェブサイトを訪問した際に広告を配信するため、第三者広告会社と提携しています。これらの会社は、氏名・住所・メール・電話番号を除く、当サイトおよび他サイトへの訪問情報を用いて、お客様の興味に合った商品・サービスの広告を提供することがあります。' },
  'cookie.s5_title': { en: '5. Managing Cookies', zh: '5. Cookieの管理' },
  'cookie.s5_p1': { en: 'You have the right to decide whether to accept or reject cookies. You can exercise your cookie rights by setting your preferences in the Cookie Consent Manager. Alternatively, you can set or amend your web browser controls to accept or refuse cookies. If you choose to reject cookies, you may still use our website though your access to some functionality and areas of our website may be restricted.', zh: 'お客様はCookieの受け入れまたは拒否を選択する権利があります。Cookie同意管理で設定するか、ブラウザの設定でCookieの受け入れ・拒否を変更できます。Cookieを拒否した場合でも当社サイトは利用できますが、一部の機能や領域へのアクセスが制限される場合があります。' },
  'cookie.s5_p2': { en: "As the means by which you can refuse cookies through your web browser controls vary from browser-to-browser, you should visit your browser's help menu for more information. Below are links to manage cookies on common browsers:", zh: 'ブラウザごとにCookie拒否の方法が異なるため、各ブラウザのヘルプメニューをご確認ください。主なブラウザのCookie管理リンクは以下のとおりです：' },
  'cookie.s5_p3': { en: 'To opt out of being tracked by Google Analytics across all websites, visit', zh: 'すべてのウェブサイトでGoogle Analyticsによるトラッキングを無効にするには、' },
  'cookie.s6_title': { en: '6. Contact Information', zh: '6. お問い合わせ' },
  'cookie.s6_intro': { en: 'If you have any questions about our use of cookies or other technologies, please contact us at:', zh: 'Cookieその他の技術の使用についてご質問がある場合は、以下までご連絡ください：' },
  'cookie.s6_company': { en: 'Jokyo Property Co., Ltd.', zh: '上京プロパティ株式会社' },
  'cookie.s6_email': { en: 'Email:', zh: '邮箱：' },
  'cookie.s6_address': { en: 'Address:', zh: '地址：' },
  'cookie.s6_website': { en: 'Website:', zh: '网站：' },
  'cookie.s7_title': { en: '7. Changes to This Policy', zh: '7. 本政策の変更' },
  'cookie.s7_p1': { en: 'We may update this Cookie Policy from time to time in order to reflect, for example, changes to the cookies we use or for other operational, legal, or regulatory reasons. Please therefore re-visit this Cookie Policy regularly to stay informed about our use of cookies and related technologies.', zh: '当社は、使用するCookieの変更やその他の運営・法的・規制上の理由により、本Cookie政策を随時更新することがあります。Cookieおよび関連技術の利用について最新の情報をご確認いただくため、定期的に本政策をご覧ください。' },
  'cookie.s7_p2': { en: 'The date at the top of this Cookie Policy indicates when it was last updated.', zh: '本Cookie政策の冒頭の日付は、最終更新日を示しています。' },

  // Privacy Policy
  'privacy.company': { en: 'Jokyo Property Co., Ltd.', zh: '上京プロパティ株式会社' },
  'privacy.title': { en: 'Privacy Policy', zh: '隐私政策' },
  'privacy.effective': { en: 'Effective Date: March 4th, 2026', zh: '生效日期：2026年3月4日' },
  'privacy.last_updated': { en: 'Last Updated: March 4th, 2026', zh: '最后更新：2026年3月4日' },
  'privacy.s1_title': { en: '1. Introduction', zh: '1. 引言' },
  'privacy.s1_p1': { en: 'Jokyo Property Co., Ltd. ("we," "us," or "our") operates a real estate search website dedicated to assisting foreign nationals in finding properties in Japan. We are committed to protecting your personal information and your right to privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website.', zh: '上京プロパティ株式会社（「当社」）は、外国籍の方が日本で物件を探すための不動産検索サイトを運営しています。当社はお客様の個人情報とプライバシーを保護することをお約束します。本隐私政策说明当您访问本网站时，我们如何收集、使用、披露及保护您的信息。' },
  'privacy.s1_p2': { en: 'Please read this privacy policy carefully. If you do not agree with the terms of this privacy policy, please do not access the site.', zh: '请仔细阅读本隐私政策。如不同意本政策条款，请勿使用本网站。' },
  'privacy.s2_title': { en: '2. Information We Collect', zh: '2. 我们收集的信息' },
  'privacy.s2_p1': { en: 'We collect information that identifies, relates to, describes, references, is capable of being associated with, or could reasonably be linked, directly or indirectly, with you ("Personal Information"). We collect the following categories of information:', zh: '我们收集可直接或间接识别、关联或描述您身份的信息（「个人信息的」）。我们收集以下类别的信息：' },
  'privacy.s2_h1': { en: 'A. Personal Information You Provide', zh: 'A. 您提供的个人信息' },
  'privacy.s2_p2': { en: 'We collect personal information that you voluntarily provide to us when you register on the website, express an interest in obtaining information about us or our products and services, or otherwise contact us. The personal information we collect depends on the context of your interactions with us and the choices you make. This includes:', zh: '当您在本网站注册、表示希望获取我们或我们产品与服务的信息或与我们联系时，我们会收集您主动提供的个人信息。收集内容取决于您与我们的互动及您的选择，包括：' },
  'privacy.s2_li1': { en: 'Full Name: To identify you as a user and prospective tenant/buyer.', zh: '姓名：用于识别用户及潜在租户/买家。' },
  'privacy.s2_li2': { en: 'Email Address: To communicate with you regarding your inquiries, property updates, and account information.', zh: '电子邮箱：用于就咨询、房源更新及账户信息与您联系。' },
  'privacy.s2_h2': { en: 'B. Information Automatically Collected', zh: 'B. 自动收集的信息' },
  'privacy.s2_p3': { en: 'We automatically collect certain information when you visit, use, or navigate the website. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, and information about how and when you use our website.', zh: '当您访问或使用本网站时，我们会自动收集部分信息。该信息不会直接暴露您的身份（如姓名或联系方式），但可能包括设备与使用信息，例如IP地址、浏览器与设备类型、操作系统、语言偏好、来源URL、设备名称、国家与位置，以及您使用本网站的方式与时间。' },
  'privacy.s3_title': { en: '3. How We Use Your Information', zh: '3. 我们如何使用您的信息' },
  'privacy.s3_p1': { en: 'We use personal information collected via our website for a variety of business purposes described below. We process your personal information for these purposes in reliance on our legitimate business interests, in order to enter into or perform a contract with you, with your consent, and/or for compliance with our legal obligations.', zh: '我们基于正当业务需要、与您订立或履行合同、经您同意和/或为履行法定义务，将通过本网站收集的个人信息用于以下业务目的。' },
  'privacy.s3_li1': { en: 'To Facilitate Property Searches: To connect you with real estate listings that match your criteria.', zh: '促进房源搜索：根据您的条件为您匹配房源。' },
  'privacy.s3_li2': { en: 'Communication: To send you administrative information, such as product, service, and new feature information, and/or information about changes to our terms, conditions, and policies.', zh: '沟通：向您发送管理类信息，如产品、服务与新功能说明，以及条款、条件与政策的变更。' },
  'privacy.s3_li3': { en: 'Service Improvement: To analyze usage trends and determine the effectiveness of our promotional campaigns to improve our website and your experience.', zh: '服务改进：分析使用趋势与推广效果，以改进网站与您的体验。' },
  'privacy.s3_li4': { en: 'Marketing: With your consent, we may send you marketing emails about new listings or services that may interest you. You can opt-out at any time.', zh: '营销：经您同意，我们可能向您发送您可能感兴趣的新房源或服务的营销邮件。您可随时选择退出。' },
  'privacy.s4_title': { en: '4. Cookies and Tracking Technologies', zh: '4. Cookie与追踪技术' },
  'privacy.s4_p1': { en: 'We use cookies and similar tracking technologies to access or store information. Specific information about how we use such technologies and how you can refuse certain cookies is set out below.', zh: '我们使用Cookie及类似追踪技术以访问或存储信息。关于使用方式及如何拒绝部分Cookie的说明见下文。' },
  'privacy.s4_ga': { en: 'Google Analytics', zh: 'Google Analytics' },
  'privacy.s4_ga_p': { en: 'We use Google Analytics to analyze user activity in order to improve the website. Google Analytics uses cookies to collect information such as your IP address, browser type, referring page, and time spent on the site. This data is aggregated and anonymized. You can opt-out of Google Analytics by installing the Google Analytics Opt-out Browser Add-on.', zh: '我们使用Google Analytics分析用户行为以改进网站。Google Analytics通过Cookie收集IP地址、浏览器类型、来源页面及停留时间等信息，数据经汇总与匿名化。您可安装Google Analytics退出浏览器插件以选择退出。' },
  'privacy.s4_adv': { en: 'Advertising Cookies', zh: '广告Cookie' },
  'privacy.s4_adv_p': { en: 'We may use third-party advertising companies to serve ads when you visit the website. These companies may use information about your visits to this and other websites contained in web cookies to provide advertisements about goods and services of interest to you.', zh: '当您访问本网站时，我们可能使用第三方广告公司投放广告。这些公司可能使用Cookie中记录的您对本网站及其他网站的访问信息，向您投放您可能感兴趣的商品与服务广告。' },
  'privacy.s4_p2': { en: 'Most web browsers are set to accept cookies by default. If you prefer, you can usually choose to set your browser to remove cookies and to reject cookies. If you choose to remove cookies or reject cookies, this could affect certain features or services of our website.', zh: '大多数浏览器默认接受Cookie。如您愿意，通常可在浏览器设置中删除或拒绝Cookie。删除或拒绝Cookie可能影响本网站的部分功能或服务。' },
  'privacy.s5_title': { en: '5. Sharing of Information', zh: '5. 信息的共享' },
  'privacy.s5_p1': { en: 'We only share information with your consent, to comply with laws, to provide you with services, to protect your rights, or to fulfill business obligations. We may process or share your data that we hold based on the following legal bases:', zh: '我们仅在征得您同意、遵守法律、向您提供服务、保护您的权利或履行业务义务时共享信息。我们可能基于以下法律依据处理或共享我们持有的您的数据：' },
  'privacy.s5_li1': { en: 'Property Owners and Agents: To facilitate the rental or purchase process, we may share your Name and Email Address with real estate agents or property owners for the properties you have inquired about.', zh: '业主与中介：为促进租赁或购买流程，我们可能向您咨询过的房源的房地产中介或业主提供您的姓名与电子邮箱。' },
  'privacy.s5_li2': { en: 'Service Providers: We may share your information with third-party vendors, service providers, contractors, or agents who perform services for us or on our behalf and require access to such information to do that work (e.g., data analysis, email delivery, hosting services).', zh: '服务提供商：我们可能向为我们或代表我们提供服务并需要访问该信息的第三方供应商、服务商、承包商或代理共享您的信息（如数据分析、邮件发送、托管服务）。' },
  'privacy.s5_li3': { en: 'Legal Obligations: We may disclose your information where we are legally required to do so in order to comply with applicable law, governmental requests, a judicial proceeding, court order, or legal process.', zh: '法律义务：为遵守适用法律、政府要求、司法程序、法院命令或法律程序，我们可能在法律要求时披露您的信息。' },
  'privacy.s6_title': { en: '6. Data Retention', zh: '6. 数据保留' },
  'privacy.s6_p1': { en: 'We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy policy, unless a longer retention period is required or permitted by law (such as tax, accounting, or other legal requirements). When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize such information.', zh: '我们仅在实现本隐私政策所述目的所需期间内保留您的个人信息，法律要求或允许更长期保留的（如税务、会计或其他法定要求）除外。当我们不再有正当业务需要处理您的个人信息时，将删除或匿名化该信息。' },
  'privacy.s7_title': { en: "7. Your Rights (Under Japanese Law)", zh: '7. 您的权利（依据日本法律）' },
  'privacy.s7_p1': { en: 'Under the Act on the Protection of Personal Information (APPI) of Japan, you have specific rights regarding your personal data held by us. These rights include:', zh: '根据日本《个人情报保护法》（APPI），您对我们持有的您的个人数据享有特定权利，包括：' },
  'privacy.s7_li1': { en: 'Right to Request Disclosure: You have the right to request that we disclose the personal data we hold about you.', zh: '请求披露权：您有权要求我们披露我们持有的您的个人数据。' },
  'privacy.s7_li2': { en: 'Right to Correction: You have the right to request the correction, addition, or deletion of your personal data if it is factually incorrect.', zh: '更正权：若个人数据与事实不符，您有权要求更正、补充或删除。' },
  'privacy.s7_li3': { en: 'Right to Suspension of Use: You have the right to request that we stop using or delete your personal data if it is being used for purposes other than those stated, or if it was acquired by improper means.', zh: '停止使用权：若数据被用于明示目的以外或通过不当手段取得，您有权要求我们停止使用或删除您的个人数据。' },
  'privacy.s7_li4': { en: 'Right to Restrict Third-Party Provision: You have the right to request that we stop providing your data to third parties if such provision violates the law.', zh: '限制向第三方提供权：若向第三方提供违反法律，您有权要求我们停止向第三方提供您的数据。' },
  'privacy.s7_p2': { en: 'To exercise any of these rights, please contact us using the contact information provided below. We will respond to your request in accordance with applicable laws.', zh: '行使上述权利时，请通过下文提供的联系方式与我们联系。我们将依法对您的请求作出回应。' },
  'privacy.s8_title': { en: '8. Security', zh: '8. 安全' },
  'privacy.s8_p1': { en: 'We have implemented appropriate technical and organizational security measures designed to protect the security of any personal information we process. However, please also remember that we cannot guarantee that the internet itself is 100% secure. Although we will do our best to protect your personal information, transmission of personal information to and from our website is at your own risk. You should only access the services within a secure environment.', zh: '我们已采取适当的技术与组织安全措施以保护我们处理的个人情报的安全。但请注意，我们无法保证互联网本身百分之百安全。我们会尽力保护您的个人信息，但通过本网站传输个人信息仍由您自行承担风险。请在安全环境中使用本服务。' },
  'privacy.s9_title': { en: "Children's Privacy", zh: '儿童隐私' },
  'privacy.s9_p1': { en: "Our services are not intended for individuals under the age of 18. We do not knowingly solicit data from or market to children under 18 years of age. By using the website, you represent that you are at least 18 or that you are the parent or guardian of such a minor and consent to such minor dependent's use of the website.", zh: '本服务不面向未满18周岁的人士。我们不会故意向未满18周岁的儿童收集数据或进行营销。使用本网站即表示您确认您已满18周岁，或您为该未成年人的父母或监护人并同意其使用本网站。' },
  'privacy.s10_title': { en: '10. Changes to This Policy', zh: '10. 本政策的变更' },
  'privacy.s10_p1': { en: 'We may update this privacy policy from time to time. The updated version will be indicated by an updated "Revised" date and the updated version will be effective as soon as it is accessible. We encourage you to review this privacy policy frequently to be informed of how we are protecting your information.', zh: '我们可能不时更新本隐私政策。更新版本将以修订日期标明，并在发布后生效。建议您经常查阅本政策以了解我们如何保护您的信息。' },
  'privacy.s11_title': { en: '11. Contact Information', zh: '11. 联系方式' },
  'privacy.s11_p1': { en: 'If you have questions or comments about this policy, or if you wish to exercise your rights under Japanese law, you may contact us at:', zh: '如对本政策有疑问或意见，或希望行使日本法律赋予的权利，请通过以下方式联系我们：' },
  'privacy.s11_address': { en: 'Address:', zh: '地址：' },
  'privacy.s11_email': { en: 'Email:', zh: '邮箱：' },
  'privacy.s12_title': { en: '12. Governing Law', zh: '12. 适用法律' },
  'privacy.s12_p1': { en: 'This Privacy Policy and any disputes related thereto shall be governed by and construed in accordance with the laws of Japan, specifically the Act on the Protection of Personal Information (APPI). Any legal action or proceeding relating to your access to or use of the website or this Privacy Policy shall be instituted in a competent court in Tokyo, Japan.', zh: '本隐私政策及其相关争议均适用日本法律（特别是《个人情报保护法》APPI）并依其解释。与您访问或使用本网站或本隐私政策有关的任何法律诉讼或程序，应在日本东京有管辖权的法院提起。' },

  // Terms of Service
  'terms.company': { en: 'Jokyo Property Co., Ltd.', zh: '上京プロパティ株式会社' },
  'terms.title': { en: 'Terms of Service', zh: '服务条款' },
  'terms.last_updated': { en: 'Last Updated: March 4th, 2026', zh: '最后更新：2026年3月4日' },
  'terms.s1_title': { en: '1. Acceptance of Terms', zh: '1. 条款的接受' },
  'terms.s1_p1': { en: 'These Terms of Service (hereinafter referred to as "Terms") govern the use of the real estate search website and services (hereinafter referred to as the "Service") provided by Jokyo Property Co., Ltd. (hereinafter referred to as the "Company," "we," "us," or "our").', zh: '本服务条款（以下简称「条款」）适用于上京プロパティ株式会社（以下简称「本公司」「我们」）提供的房地产搜索网站及服务（以下简称「服务」）的使用。' },
  'terms.s1_p2': { en: 'By accessing, browsing, or using the Service, you (hereinafter referred to as the "User") acknowledge that you have read, understood, and agree to be bound by these Terms. If you do not agree to these Terms, you must immediately cease using the Service. These Terms constitute a legally binding agreement between you and the Company.', zh: '访问、浏览或使用本服务即表示您（以下简称「用户」）已阅读、理解并同意受本条款约束。如不同意本条款，请立即停止使用本服务。本条款构成您与本公司之间具有法律约束力的协议。' },
  'terms.s2_title': { en: '2. Description of Service', zh: '2. 服务说明' },
  'terms.s2_p1': { en: 'The Service is a platform specifically designed to assist foreign nationals in finding real estate properties in Japan. The Service provides users with access to property listings, search tools, and related information to facilitate the process of renting or purchasing real estate in Japan.', zh: '本服务是专为协助外国人在日本寻找房地产而设的平台，为用户提供房源列表、搜索工具及相关信息，以方便在日本租赁或购买房地产。' },
  'terms.s2_p2': { en: 'The Company acts as an information provider and intermediary platform. While we strive to provide accurate information, the Company does not own the properties listed unless explicitly stated otherwise.', zh: '本公司作为信息提供方与中介平台。我们力求提供准确信息，但除非另有明确说明，本公司不拥有所列房产。' },
  'terms.s3_title': { en: '3. User Eligibility', zh: '3. 用户资格' },
  'terms.s3_p1': { en: 'The Service is intended for use by individuals who are currently residing in Japan or are planning to move to Japan. By using the Service, you represent and warrant that:', zh: '本服务面向目前居住在日本或计划移居日本的人士。使用本服务即表示您声明并保证：' },
  'terms.s3_li1': { en: 'You are at least 18 years of age or possess legal parental or guardian consent.', zh: '您已满18周岁或已获得法定父母或监护人同意。' },
  'terms.s3_li2': { en: 'You have the legal capacity to enter into a binding contract under Japanese law.', zh: '您具有根据日本法律订立有约束力合同的法律能力。' },
  'terms.s3_li3': { en: 'All information you provide to the Company is truthful and accurate.', zh: '您向本公司提供的所有信息真实、准确。' },
  'terms.s4_title': { en: '4. User Account & Registration', zh: '4. 用户账户与注册' },
  'terms.s4_p1': { en: 'To access certain features of the Service, such as saving property searches or contacting agents, you may be required to register for an account.', zh: '为使用保存房源搜索或联系中介等部分功能，您可能需要注册账户。' },
  'terms.s4_h1': { en: '4.1 Registration Information', zh: '4.1 注册信息' },
  'terms.s4_p2': { en: 'When creating an account, you agree to provide accurate, current, and complete information, specifically your full name and email address. You are responsible for maintaining the confidentiality of your account credentials.', zh: '注册时，您同意提供准确、最新且完整的信息，尤其是姓名与电子邮箱。您有责任对账户凭据保密。' },
  'terms.s4_h2': { en: '4.2 Account Security', zh: '4.2 账户安全' },
  'terms.s4_p3': { en: 'You are solely responsible for all activities that occur under your account. You agree to notify the Company immediately of any unauthorized use of your account or any other breach of security. The Company will not be liable for any loss or damage arising from your failure to comply with this section.', zh: '您对账户下发生的一切活动负全部责任。您同意在发现账户遭未经授权使用或发生其他安全漏洞时立即通知本公司。因您未遵守本条而产生的任何损失或损害，本公司不承担责任。' },
  'terms.s5_title': { en: '5. Prohibited Activities', zh: '5. 禁止行为' },
  'terms.s5_p1': { en: 'In using the Service, you agree not to engage in any of the following prohibited activities:', zh: '使用本服务时，您同意不从事以下禁止行为：' },
  'terms.s5_li1': { en: 'Violating any applicable laws, regulations, or third-party rights.', zh: '违反任何适用法律、法规或第三方权利。' },
  'terms.s5_li2': { en: 'Using the Service for any fraudulent or illegal purpose.', zh: '以欺诈或非法目的使用本服务。' },
  'terms.s5_li3': { en: 'Submitting false, misleading, or inaccurate information.', zh: '提交虚假、误导或不准确的信息。' },
  'terms.s5_li4': { en: 'Attempting to interfere with, compromise the system integrity or security, or decipher any transmissions to or from the servers running the Service.', zh: '试图干扰、破坏系统完整性或安全性，或破译与服务服务器之间的任何传输。' },
  'terms.s5_li5': { en: 'Copying, distributing, or disclosing any part of the Service in any medium, including without limitation by any automated or non-automated "scraping."', zh: '以任何形式复制、分发或披露本服务的任何部分，包括但不限于任何自动化或非自动化的「爬取」。' },
  'terms.s5_li6': { en: 'Using the Service to send spam, unsolicited communications, or chain letters.', zh: '利用本服务发送垃圾邮件、未经请求的通讯或连锁信。' },
  'terms.s5_li7': { en: 'Impersonating another person or otherwise misrepresenting your affiliation with a person or entity.', zh: '冒充他人或虚假陈述您与某个人或实体的关系。' },
  'terms.s6_title': { en: '6. Intellectual Property', zh: '6. 知识产权' },
  'terms.s6_p1': { en: 'All content included on the Service, such as text, graphics, logos, images, as well as the compilation thereof, and any software used on the Service, is the property of TK LLC. or its suppliers and protected by copyright and other laws that protect intellectual property and proprietary rights.', zh: '本服务所载全部内容（包括但不限于文字、图形、标识、图片及其汇编）以及本服务所使用的任何软件，均为 TK LLC. 或其供应商的财产，受著作权及其他知识产权与专有权利法律保护。' },
  'terms.s6_p2': { en: 'You are granted a limited, non-exclusive, non-transferable license to access and use the Service strictly in accordance with these Terms. You agree not to modify, publish, transmit, reverse engineer, participate in the transfer or sale, create derivative works, or in any way exploit any of the content, in whole or in part.', zh: '您被授予一项有限、非排他、不可转让的许可，仅可严格按照本条款访问和使用本服务。您同意不修改、发布、传播、反向工程、参与转让或出售、创作衍生作品或以任何方式利用全部或部分内容。' },
  'terms.s7_title': { en: '7. Disclaimer of Warranties', zh: '7. 免责声明' },
  'terms.s7_p1': { en: 'The Service is provided on an "AS IS" and "AS AVAILABLE" basis. To the fullest extent permitted by law, the Company expressly disclaims all warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.', zh: '本服务按「现状」和「可用性」提供。在法律允许的最大范围内，本公司明确否认任何形式的明示或暗示保证，包括但不限于适销性、特定用途适用性及不侵权的默示保证。' },
  'terms.s7_p2': { en: 'The Company makes no warranty that (i) the Service will meet your requirements; (ii) the Service will be uninterrupted, timely, secure, or error-free; (iii) the results that may be obtained from the use of the Service will be accurate or reliable; or (iv) the quality of any products, services, information, or other material obtained by you through the Service will meet your expectations.', zh: '本公司不保证：(i) 本服务将满足您的要求；(ii) 本服务将不中断、及时、安全或无错误；(iii) 使用本服务所获结果将准确或可靠；或 (iv) 您通过本服务获得的任何产品、服务、信息或其他材料的质量将满足您的期望。' },
  'terms.s8_title': { en: '8. Limitation of Liability', zh: '8. 责任限制' },
  'terms.s8_p1': { en: 'To the maximum extent permitted by applicable law, in no event shall Jokyo Property Co., Ltd., its affiliates, agents, directors, employees, suppliers, or licensors be liable for any direct, indirect, punitive, incidental, special, consequential, or exemplary damages, including without limitation damages for loss of profits, goodwill, use, data, or other intangible losses, arising out of or relating to the use of, or inability to use, the Service.', zh: '在适用法律允许的最大范围内，上京プロパティ株式会社及其关联方、代理、董事、员工、供应商或许可方均不对因使用或无法使用本服务而产生的任何直接、间接、惩罚性、附带、特别、后果性或示范性损害承担责任，包括但不限于利润、商誉、使用、数据或其他无形损失。' },
  'terms.s8_p2': { en: 'The Company assumes no liability or responsibility for any (i) errors, mistakes, or inaccuracies of content; (ii) personal injury or property damage, of any nature whatsoever, resulting from your access to and use of our Service; or (iii) any unauthorized access to or use of our secure servers and/or any and all personal information stored therein.', zh: '本公司对以下各项不承担任何责任：(i) 内容的错误、过失或不准确；(ii) 因您访问和使用本服务而产生的任何人身伤害或财产损失；(iii) 对安全服务器和/或其中存储的任何个人信息的未经授权访问或使用。' },
  'terms.s9_title': { en: '9. Governing Law', zh: '9. 适用法律' },
  'terms.s9_p1': { en: 'These Terms shall be governed by and construed in accordance with the laws of Japan, without regard to its conflict of law provisions. Any dispute arising from or relating to the subject matter of these Terms shall be subject to the exclusive jurisdiction of the Tokyo District Court or the Tokyo Summary Court as the court of first instance.', zh: '本条款适用日本法律并依其解释，不适用法律冲突规则。因本条款主题或与之相关的任何争议，由东京地方法院或东京简易法院作为一审管辖法院专属管辖。' },
  'terms.s10_title': { en: '10. Changes to Terms', zh: '10. 条款的变更' },
  'terms.s10_p1': { en: "The Company reserves the right, at its sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.", zh: '本公司保留随时自行修改或替换本条款的权利。若修订具有实质性，我们将尽量在新条款生效前至少提前30日通知。是否构成实质性变更由本公司自行判断。' },
  'terms.s10_p2': { en: 'By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.', zh: '在该等修订生效后继续访问或使用本服务，即表示您同意受修订后条款的约束。如不同意新条款，请停止使用本服务。' },
  'terms.s11_title': { en: '11. Contact Information', zh: '11. 联系方式' },
  'terms.s11_p1': { en: 'If you have any questions about these Terms, please contact us at:', zh: '如对本条款有任何疑问，请通过以下方式联系我们：' },
  'terms.s11_email': { en: 'Email:', zh: '邮箱：' },
  'terms.s11_address': { en: 'Address:', zh: '地址：' },
  'terms.copyright': { en: '© 2026 TK LLC. All rights reserved.', zh: '© 2026 TK LLC. 保留所有权利。' }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const path = window.location.pathname;
    return path.startsWith('/zh/') || path === '/zh' ? 'zh' : 'en';
  });

  // Sync <html lang=""> with current language (for Chinese font and a11y)
  React.useEffect(() => {
    document.documentElement.lang = language === 'zh' ? 'zh-Hans' : 'en';
  }, [language]);

  // Sync language changes with the URL
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    const path = window.location.pathname;
    const isZh = path.startsWith('/zh/') || path === '/zh';
    
    if (lang === 'zh' && !isZh) {
      // Add /zh prefix
      const newPath = path === '/' ? '/zh' : `/zh${path}`;
      window.history.replaceState(null, '', `${newPath}${window.location.search}`);
    } else if (lang === 'en' && isZh) {
      // Remove /zh prefix
      const newPath = path === '/zh' ? '/' : path.substring(3);
      window.history.replaceState(null, '', `${newPath}${window.location.search}`);
    }
  };

  const t = (key: string): string => {
    if (!translations[key]) {
      console.warn(`Translation key not found: ${key}`);
      return key;
    }
    return translations[key][language];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}