import { createContext, useContext, useMemo, type ReactNode } from 'react';

/** 日本語のみ（言語切替なし） */
const UI_STRINGS: Record<string, string> = {
  // Navigation
  'app.title': '不動産検索ツール',
  'nav.home': 'トップ',
  'nav.buy': '一覧',
  'nav.register': '物件登録',
  'nav.rent': '賃貸',
  'nav.blog': 'ブログ',
  'nav.about': '情報',
  'nav.consultation': '相談',
  'nav.account': 'アカウント',
  'nav.signin': 'ログイン',
  
  // Hero Section
  'hero.title.1': '',
  'hero.subtitle': '条件を指定してデータベースを検索します。',
  'hero.btn.consultation': '',
  'hero.btn.social': '',
  
  // Quick Search
  'search.title': '検索条件',
  'search.buy': '購入',
  'search.rent': '賃貸',
  'search.area.label': 'エリア',
  'search.area.placeholder': 'エリアを選択',
  'search.type.label': '物件タイプ',
  'search.type.placeholder': 'タイプを選択',
  'search.price.label': '価格帯',
  'search.price.placeholder': '価格指定なし',
  'search.btn': '検索',
  'search.btn_short': '検索',
  'search.placeholder.keyword': 'タイトル、住所、駅で検索...',
  'search.area.select': 'エリアを選択',
  'search.area.one': '1エリア',
  'search.area.many': '{n}エリア',
  'search.area.search_placeholder': 'エリアを検索...',
  'search.budget.any': '指定なし',
  'search.budget.any_budget': '予算指定なし',
  'search.budget.price': '価格',
  'search.budget.monthly_rent': '月額家賃',
  'search.bedrooms.label': '間取り',
  'search.bedrooms.studio': 'スタジオ',
  'search.bedrooms.1br': '1LDK',
  'search.bedrooms.2br': '2LDK',
  'search.bedrooms.3br': '3LDK',
  'search.bedrooms.4br_plus': '4LDK以上',
  'search.budget.under_50m': '5,000万円以下',
  'search.budget.50m_80m': '5,000万円–8,000万円',
  'search.budget.80m_120m': '8,000万円–1.2億円',
  'search.budget.120m_200m': '1.2億円–2億円',
  'search.budget.over_200m': '2億円以上',
  'search.budget.under_150k': '15万円以下/月',
  'search.budget.150k_250k': '15万円–25万円/月',
  'search.budget.250k_400k': '25万円–40万円/月',
  'search.budget.400k_600k': '40万円–60万円/月',
  'search.budget.over_600k': '60万円以上/月',
  'search.size.label': '物件面積 (m²)',
  'search.size.from': '最小',
  'search.size.to': '最大',
  'search.size.placeholder_min': '例: 30',
  'search.size.placeholder_max': '例: 80',
  'search.area.header': '東京23区 + 23区外',
  'search.area.no_match': '該当するエリアがありません',
  'search.area.label_short': 'エリア',

  // Tokyo ward names (23 wards + Outer 23 + outer cities for Tokyo Wards section)
  'ward.Chiyoda': '千代田区',
  'ward.Chuo': '中央区',
  'ward.Minato': '港区',
  'ward.Shinjuku': '新宿区',
  'ward.Bunkyo': '文京区',
  'ward.Taito': '台東区',
  'ward.Sumida': '墨田区',
  'ward.Koto': '江東区',
  'ward.Shinagawa': '品川区',
  'ward.Meguro': '目黒区',
  'ward.Ota': '大田区',
  'ward.Setagaya': '世田谷区',
  'ward.Shibuya': '渋谷区',
  'ward.Nakano': '中野区',
  'ward.Suginami': '杉並区',
  'ward.Toshima': '豊島区',
  'ward.Kita': '北区',
  'ward.Arakawa': '荒川区',
  'ward.Itabashi': '板橋区',
  'ward.Nerima': '練馬区',
  'ward.Adachi': '足立区',
  'ward.Katsushika': '葛飾区',
  'ward.Edogawa': '江戸川区',
  'ward.Outside23': '23区外',
  'ward.Hachioji': '八王子市',
  'ward.Tachikawa': '立川市',
  'ward.Musashino': '武蔵野市',
  'ward.Mitaka': '三鷹市',
  'ward.Ome': '青梅市',
  'ward.Fuchu': '府中市',
  'ward.Akishima': '昭島市',
  'ward.Chofu': '調布市',
  'ward.Machida': '町田市',
  'ward.Koganei': '小金井市',
  'ward.Kodaira': '小平市',
  'ward.Hino': '日野市',
  'ward.Higashimurayama': '東村山市',
  'ward.Kokubunji': '国分寺市',
  'ward.Kunitachi': '国立市',
  'ward.Fussa': '福生市',
  'ward.Komae': '狛江市',
  'ward.Higashiyamato': '東大和市',
  'ward.Kiyose': '清瀬市',
  'ward.Higashikurume': '東久留米市',
  'ward.Musashimurayama': '武蔵村山市',
  'ward.Tama': '多摩市',
  'ward.Inagi': '稲城市',
  'ward.Hamura': '羽村市',
  'ward.Akiruno': 'あきる野市',
  'ward.Nishitokyo': '西東京市',

  // Sections
  'section.featured.title': '新着登録物件',
  'section.featured.subtitle': '',
  'section.areas.title': '物件種別',
  'section.areas.subtitle': '種別をタップして一覧へ絞り込み',
  'section.areas.explore_title': 'エリア',
  'section.areas.explore_desc': '',
  'section.areas.wards23': '主要カテゴリ',
  'section.areas.outer': 'その他カテゴリ',
  'section.areas.view_rentals': '一覧を見る',
  'section.areas.view_sale': '売買を見る',
  'section.areas.show_more': 'もっと見る',
  'section.areas.show_less': '閉じる',
  'section.areas.properties_count': '物件 {n} 件',
  'section.featured.view_all': '一覧へ',
  'section.featured.view_all_properties': 'すべての物件を見る',
  'section.featured.loading': '読み込み中...',
  'section.featured.empty': '該当データなし',
  'section.featured.swipe': 'スワイプ',
  'section.categories.title': 'カテゴリから探す',
  'section.categories.properties_count': '物件 {n} 件',
  'category.pet_friendly': 'ペット可',
  'search.advanced_filters': '詳細条件',
  'section.why.title': '選ばれる理由',
  'section.why.subtitle': '信頼できる日本の不動産パートナー',

  // Why Us
  'why.support.title': '丁寧なサポート',
  'why.support.desc': '日本語・英語など、ご希望に合わせてコミュニケーションいたします。',
  'why.process.title': '透明なプロセス',
  'why.process.desc': '費用・契約・法令上の要件をわかりやすくご説明します。',
  'why.network.title': '豊富な物件情報',
  'why.network.desc': '東京エリアの優良物件を幅広くご紹介します。',

  // Trust Section
  'trust.brokerage.title': '免許を持つ正規の不動産会社',
  'trust.brokerage.desc': '宅建業法に基づき登録し、法令を遵守した透明な取引を行います。',
  'trust.multilingual.title': '多言語サポート',
  'trust.multilingual.desc': '契約内容の説明から価格交渉、手続きまでサポートします。',
  'trust.specialist.title': '海外のお客様に強いチーム',
  'trust.specialist.desc': '外国籍の方の賃貸・購入の実績が豊富です。',

  // Process Section
  'process.title': 'サービスの流れ',
  'process.step1.title': '初回相談',
  'process.step1.desc': 'メール、LINE、フォームなどでご連絡ください。ご希望（購入・賃貸）、予算、エリア、スケジュールをお聞かせください。',
  'process.step2.title': '物件のご提案',
  'process.step2.desc': '条件に合う物件を厳選し、次の情報をお届けします。',
  'process.step2.list1': '写真・間取り',
  'process.step2.list2': '価格の詳細',
  'process.step2.list3': '想定される初期費用',
  'process.step2.list4': '物件のポイント',
  'process.step3.title': '内見・申込',
  'process.step3.desc': '現地またはオンラインで内見を手配します。気に入った物件の申込・条件交渉もサポートします。',
  'process.step4.title': '契約・お引き渡し',
  'process.step4.desc': '契約内容をわかりやすくご説明し、お支払い・鍵のお渡しまでサポートします。',
  'process.step3.heading': '内見（現地・オンライン）',
  'process.step3.desc_long': '現地内見またはオンライン内見が可能です。建物の状態や周辺環境もご説明します。',
  'process.step4.heading': '申込・購入の申し出',
  'process.step4.desc_rent': '賃貸：賃貸借申込に必要な書類をご案内します。',
  'process.step4.desc_buy': '売買：正式な購入申込書の準備・提出をサポートします。',
  'process.step5.heading': '審査・価格交渉',
  'process.step5.desc_rent': '賃貸：家主様の審査（目安2〜5営業日）。',
  'process.step5.desc_buy': '売買：価格・条件のすり合わせを行います。',
  'process.step6.heading': '契約書の準備と説明',
  'process.step6.desc': '契約書を準備し、署名前に内容を丁寧にご説明します。',
  'process.step7.heading': 'お支払い・最終手続き',
  'process.step7.desc_rent': '賃貸：敷金・礼金・仲介手数料などの入居時費用',
  'process.step7.desc_buy': '売買：手付金・残金のお支払い',
  'process.step7.guide': 'お支払いの流れもサポートします。',
  'process.step8.heading': '鍵のお渡し',
  'process.step8.desc': '手続き完了後、鍵をお渡しして入居です。',
  'why.section.title': 'Tokyo Expat Housing が選ばれる理由',
  'why.multilingual.title': '多言語でのサポート',
  'why.multilingual.desc': '物件探しから契約まで、言語の壁を越えてサポートします。',
  'why.approval.title': '審査・手続きのサポート',
  'why.approval.desc': '外国人の方にも対応しやすい物件・保証の選択をご案内します。',
  'why.fast.title': 'スピーディかつ透明な対応',
  'why.fast.desc': 'スケジュールを明確にし、価格や書類の説明も丁寧に行います。',
  'cta.title': '',
  'cta.desc': '',
  'cta.book': '',
  'cta.browse': '一覧へ',
  'footer.follow': '',
  'footer.social.open': '開く',
  'internal.placeholder': '公開サイト向けの案内文・規約本文は表示していません。',
  'internal.consultation': '顧客向けの相談フォームはこの画面では使用していません。',
  'footer.mailto.subject': 'お問い合わせ',
  'footer.mailto.body': 'こんにちは、\n\n',
  'about.mailto.subject': 'お問い合わせ',
  'about.mailto.body': 'お問い合わせ内容：',
  'property.loading': '読み込み中...',
  'property.tour.signin_required': '内見を予約するにはログインしてください。',
  'property.tour.submit_error': '送信に失敗しました。もう一度お試しください。',
  'property.tour.time_range': '時間帯',
  'property.tour.option_n': '候補 {n}',
  'listing.title.rent': '賃貸物件',
  'listing.title.rent.ward': '{ward}の賃貸物件',
  'listing.results_count': '{count} 件',
  'listing.monthly_rent_label': '月額家賃：',
  'activity.details_requested': '資料請求済み',
  'activity.room_tour_booked': '内見予約済み',
  'activity.for_rent': '賃貸',
  'activity.for_sale': '売買',
  'listing.properties_found': '物件 {count} 件',
  'account.activity': '申請履歴',
  'account.profile': 'プロフィール',
  'account.logout': 'ログアウト',
  'account.user': 'ユーザー',
  'activity.title': '申請した物件',
  'activity.subtitle': '内見予約・資料請求した物件を確認できます。',
  'activity.preferred_tour_dates': '希望の内見日',
  'activity.no_rent': '賃貸の申請履歴はありません。',
  'activity.no_buy': '売買の申請履歴はありません。',

  'profile.title': 'プロフィール',
  'profile.tab_information': '基本情報',
  'profile.tab_password': 'パスワード',
  'profile.first_name': '名',
  'profile.last_name': '姓',
  'profile.email_address': 'メールアドレス',
  'profile.saved_success': '保存しました。',
  'profile.saved_error': '保存に失敗しました。もう一度お試しください。',
  'profile.saving': '保存中...',
  'profile.save': '保存',
  'profile.current_password': '現在のパスワード',
  'profile.new_password': '新しいパスワード',
  'profile.password_placeholder': '8文字以上',
  'profile.confirm_password': '新しいパスワード（確認）',
  'profile.password_success': 'パスワードを更新しました。',
  'profile.password_error': '更新に失敗しました。現在のパスワードを確認するか、8文字以上で入力してください。',
  'profile.updating': '更新中...',
  'profile.update_password': 'パスワードを更新',

          // Property Detail
          'property.back': '戻る',
          'property.photo': '写真',
          'property.brochure': 'パンフレット',
          'property.initial_fees_card': '初期費用はクレジットカードでお支払いいただけます',
          'property.initial_fees_card_note': '※別途手数料がかかる場合があります',
  'property.tour.title': '内見・見学の予約',
  'property.tour.request_room_tour': '内見を予約',
  'property.tour.date1': '希望日 1',
  'property.tour.date2': '希望日 2',
  'property.tour.date3': '希望日 3',
  'property.tour.name': 'お名前',
  'property.tour.email': 'メール',
  'property.tour.submit': '予約を送信',
  'property.tour.success': '内見のご予約を受け付けました。担当者よりご連絡いたします。',
  'property.tour.preferred_times_error': '希望時間の保存に失敗しました。もう一度お試しください。',
  'property.tour.confirm': '確認',
  'property.back_to_list': '一覧に戻る',
  'property.inquiry.title': 'この物件について問い合わせ',
  'property.inquiry.name': 'お名前',
  'property.inquiry.email': 'メール',
  'property.inquiry.message': 'メッセージ（任意）',
  'property.inquiry.submit': '送信する',
  'property.inquiry.success': 'お問い合わせを送信しました。',
  'property.overview': '概要',
  'property.description': '物件説明',
  'property.location': '所在地',
  'property.features': '設備・特徴',
  'property.readMore': '続きを読む',
  'property.showLess': '閉じる',
  'property.information': '物件情報',
  'property.type': '種別',
  'property.layout': '間取り',
  'property.size': '専有面積',
  'property.built': '築年',
          'property.floor': '所在階',
          'property.station': '最寄り駅',
          'property.notfound': '物件が見つかりません',
          'error.fetch_failed': '読み込みに失敗しました。通信環境をご確認のうえ、再度お試しください。',
          'common.retry': '再試行',
          'property.price.rent': '月額家賃',
          'property.price.buy': '価格',
          'property.feature.pet': 'ペット可',
          'property.feature.foreign': '外国籍の方歓迎',
          'property.feature.balcony': 'バルコニー',
          'property.feature.bicycle': '駐輪場',
          'property.feature.delivery': '宅配ボックス',
          'property.feature.elevator': 'エレベーター',
          'property.feature.south': '南向き',
          'property.tour.instruction': '希望日時を最大3つまでご入力ください。こちらから日程を調整します。',
          'property.tour.option': '候補',
          'property.tour.date': '日付',
          'property.tour.time': '時間',
          'property.tour.time.any': '指定なし',
          'property.tour.time.morning': '午前',
          'property.tour.time.afternoon': '午後',
          'property.tour.time.evening': '夕方',
          'property.placeholder.name': 'お名前',
          'property.placeholder.email': 'メールアドレス',
          'property.placeholder.message': 'ご質問があればご記入ください',
          'property.sending': '送信中...',
          'property.walk.min': '分徒歩',
          'property.walk.min_short': '分',
          'property.check_availability.title': '空室状況・詳細資料のご請求',
          'property.check_availability.btn': '空室を確認',
          'property.check_availability.desc': 'お名前とメールアドレスをご入力ください。空室状況や詳細資料をお送りします。',
          'property.check_availability.name': 'お名前',
          'property.check_availability.email': 'メールアドレス',
          'property.check_availability.success': '送信しました。担当者が24時間以内にご連絡いたします。',
          'property.bed': '室',
          'property.bath': 'バス',
          'property.management_fee': '管理費',
          'property.deposit': '敷金',
          'property.no_deposit': '敷金なし',
          'property.key_money': '礼金',
          'property.no_key_money': '礼金なし',
          'property.bedrooms': '寝室数',
          'property.rental_fees': '賃貸に関する費用',

          // Listing & Filters
          'filter.title': '絞り込み',
          'filter.expand_filters': '条件を表示',
          'filter.collapse_filters': '条件をたたむ',
          'filter.show_map': '地図を表示',
          'map.loading': '地図を読み込み中...',
          'map.no_address': '住所が登録されていません。',
          'map.geocode_error': '住所から位置を取得できませんでした。',
          'map.cannot_display': '地図を表示できません。',
          'map.property_location': '物件の位置',
          'map.cluster_count': '物件 {n} 件',
          'map.click_to_zoom': 'クリックで拡大',
          'map.view_details_new_tab': '詳細を見る（新しいタブ）',
          'map.bed': '室',
          'map.no_properties': '地図上に表示する物件がありません。',
          'map.view_details': '詳細を見る',
          'filter.hide': '非表示',
          'filter.show': '表示',
          'filter.search': '検索',
          'filter.property_type': '物件タイプ',
          'filter.type.apartment': 'アパート',
          'filter.type.condominium': 'マンション',
          'filter.type.house': '一戸建て',
          'filter.type.studio': 'ワンルーム',
          'filter.station': '駅',
          'filter.selected_area': 'エリア',
          'filter.price': '価格',
          'filter.price_range': '価格帯',
          'filter.no_min': '下限なし',
          'filter.no_max': '上限なし',
          'filter.size': '専有面積 (m²)',
          'filter.bedrooms': '間取り',
          'filter.bedrooms.any': '指定なし',
          'filter.all': 'すべて',
          'filter.listing_type': '種別：',
          'filter.keyword_placeholder': 'キーワード...',
          'filter.min_yen': '最低 ¥',
          'filter.max_yen': '最高 ¥',
          'filter.min_sqm': '最小 m²',
          'filter.max_sqm': '最大 m²',
          'filter.station_placeholder': '駅名...',
          'filter.more_filters': 'さらに詳しく',
          'filter.categories': 'カテゴリ',
          'filter.save': '保存',
          
          'category.luxury': '高級',
          'category.furnished': '家具付き',
          'category.high_rise': 'タワーマンション',
          'category.no_key_money': '礼金なし',
          'category.students': '学生向け',
          'category.designers': 'デザイナーズ',
          'category.families': 'ファミリー向け',
          'category.foreign_friendly': '外国籍の方歓迎',

          'sort.price_asc': '価格（安い順）',
          'sort.price_desc': '価格（高い順）',
          'sort.size_asc': '面積（小さい順）',
          'sort.size_desc': '面積（大きい順）',
          'sort.walking_asc': '駅から近い順',
          'sort.walking_desc': '駅から遠い順',
          'sort.newest': '新着順',
          'sort.oldest': '古い順',
          'sort.label': '並び替え',
          'listing.title': '売買物件',
          'listing.title.ward': '{ward}の売買物件',
          'listing.results': '{count} 件',
          'listing.loading': '読み込み中...',
          'listing.error': 'エラー: {error}',
          'listing.empty': '該当する物件がありません。',
          'listing.badge.popular': '人気',
          'listing.badge.new': '新着',

          'listing.load_more': 'さらに読み込む',
  'property.download_pdf': 'PDFをダウンロード',

          // Consultation
          'consult.title': '無料相談',
          'consult.desc': 'ご希望や目的をお聞かせください。24時間以内にご連絡し、面談やお打ち合わせの日程を調整いたします。',
          'consult.thank_you': 'ありがとうございました',
          'consult.success_desc': 'お問い合わせを受け付けました。担当者が24時間以内にご連絡いたします。',
          'consult.back_home': 'トップへ戻る',
          'consult.name': 'お名前 *',
          'consult.name_ph': '山田 太郎',
          'consult.email': 'メール *',
          'consult.email_ph': 'you@example.com',
          'consult.phone': '電話番号',
          'consult.phone_ph': '電話番号',
          'consult.search_country': '国を検索...',
          'consult.interest': 'ご関心のある内容',
          'consult.interest_rent': '賃貸',
          'consult.interest_buy': '購入',
          'consult.date': 'ご希望の日時',
          'consult.online': 'オンライン（Zoom / Google Meet 等）を希望',
          'consult.message': 'ご相談内容',
          'consult.message_ph': 'ご予算・希望エリア・その他ご要望をご記入ください',
          'consult.submit': '送信する',

          // About Us
          'about.title': '会社概要',
          'about.p1': 'Tokyo Expat Housing（上京プロパティ株式会社運営）は、東京を拠点とする不動産サービスです。海外在住の方や留学生、グローバルなお客様をサポートします。',
          'about.p2': '分かりやすいご説明、透明な料金体系、多言語サポートで、東京での理想の住まい探しをお手伝いします。',
          'about.p3': '国際的な経験を持つチームが、文化やコミュニケーションの違いを踏まえ、日本での住まい探しの課題に寄り添います。',
          'about.p4': '日本の住まい探しは、保証人や契約手続きなど複雑に感じられることがあります。当社は手続きをわかりやすく整理し、各段階で正確で分かりやすいサポートを行います。',
          'about.company_profile': '会社情報',
          'about.company_name': '会社名',
          'about.company_name_val': '上京プロパティ株式会社',
          'about.license': '免許番号',
          'about.license_val': '東京都知事（1）第113518号',
          'about.corporate_number': '法人番号',
          'about.director': '代表取締役',
          'about.director_val': 'Kosei Kudo',
          'about.address': '所在地',
          'about.address_val': '〒170-0004 東京都豊島区北大塚3-1-5 77Space 102',
          'about.phone': '電話',
          'about.email': 'メール',

          // Blog
          'blog.title': 'ブログ',
          'blog.all': 'すべて',
          'blog.loading': '記事を読み込み中...',
          'blog.error': 'エラー',
          'blog.error_desc': '記事を読み込めませんでした。',
          'blog.not_found': '記事が見つかりません。',
          'blog.back_to_list': 'ブログ一覧に戻る',
          'blog.preparing': '準備中',

          // Footer
  'footer.about': 'Tokyo Expat Housing は、東京エリアの不動産を中心に、お客様の住まい探しをサポートします。',
  'footer.quickLinks': 'クイックリンク',
  'footer.contact': 'お問い合わせ',
  'footer.address': '東京都',
  'footer.rights': '© 2026 Tokyo Expat Housing. All rights reserved.',
  'footer.operated_by': '運営：上京プロパティ株式会社',
  'footer.license': '東京都知事（1）第113518号',
  'footer.address_line1': '東京都豊島区北大塚3-1-5 77Space 102',
  'footer.address_line2': '〒170-0004 日本',
  'footer.services': 'サービス',
  'footer.buy_property': '購入',
  'footer.rent_live': '賃貸',
  'footer.company': '会社情報',
  'footer.copyright': '© 2026 TK LLC. All rights reserved.',
  'footer.privacy_policy': 'プライバシーポリシー',
  'footer.terms_of_service': '利用規約',
  'footer.cookie_policy': 'Cookieポリシー',

  // Cookie Policy（スタブ画面の見出しのみ使用）
  'cookie.title': 'Cookie',
  'cookie.last_updated': '最終更新：2026年3月4日',
  'cookie.intro1': '上京プロパティ株式会社（「当社」「私たち」）は、当社ウェブサイト（「サービス」）において、他の利用者とお客様を区別するためにCookieおよび類似のトラッキング技術を使用しています。これにより、ウェブサイトの閲覧体験の向上、サイトの改善、および関連コンテンツ・広告の表示が可能になります。',
  'cookie.intro2': '本Cookie政策では、Cookieとは何か、当社の使用方法、使用するCookieの種類、お客様の選択肢、およびCookieに関する詳細について説明します。本政策は、個人情報の保護に関する法律（APPI）を含む日本国内の適用法令に準拠しています。',
  'cookie.s1_title': '1. Cookieとは',
  'cookie.s1_p1': 'Cookieは、ウェブサイトにアクセスした際に、お客様のコンピュータ、モバイル端末、またはタブレットに保存される小さなテキストファイルです。ウェブサイトの動作や効率化、およびレポート情報の提供のために、サイト運営者によって広く利用されています。',
  'cookie.s1_p2': 'ウェブサイト運営者（ここでは上京プロパティ株式会社）が設定するCookieは「ファーストパーティCookie」、それ以外が設定するCookieは「サードパーティCookie」と呼ばれます。サードパーティCookieにより、広告・インタラクティブコンテンツ・分析など、第三者による機能がサイト上で提供されます。',
  'cookie.s2_title': '2. Cookieの使用方法',
  'cookie.s2_p1': '当社は、以下に詳述する様々な目的でCookieを使用しています。多くの場合、Cookieが提供する機能を維持したまま無効にする業界標準の方法はありません。必要かどうか不明な場合は、利用中のサービスにCookieが使われている可能性があるため、すべてのCookieを有効のままにしておくことを推奨します。',
  'cookie.s2_specifically': '具体的には、当社はCookieを次の目的で使用します：',
  'cookie.s2_li1': 'ウェブサイトが正しく動作するようにする。',
  'cookie.s2_li2': '当社ウェブサイトの利用状況を把握し、サービスを改善する。',
  'cookie.s2_li3': '言語や検索条件などの設定・嗜好を記憶する。',
  'cookie.s2_li4': 'お客様の興味に合った広告を配信する。',
  'cookie.s3_title': '3. 使用するCookieの種類',
  'cookie.s3_h1': '厳密に必要なCookie',
  'cookie.s3_p1': 'これらのCookieは、サイトの閲覧や安全な領域へのアクセスなどの機能に不可欠です。これらがないと、ご要望いただいたサービスを提供できません。サイト運営に必要なため、同意なく使用します。',
  'cookie.s3_h2': 'Analytics and Performance Cookies（分析・パフォーマンスCookie）',
  'cookie.s3_p2': 'これらのCookieは、最も閲覧したページやエラーメッセージの有無など、当社ウェブサイトの利用方法に関する情報を収集します。個人を特定する情報は収集せず、集約された匿名データのみを使用し、サイトの改善に役立てます。',
  'cookie.s3_h3': 'Advertising and Targeting Cookies（広告・ターゲティングCookie）',
  'cookie.s3_p3': 'これらのCookieは、お客様の興味に合った広告の配信、広告表示回数の制限、広告効果の測定に使用されます。通常、サイト運営者の許可を得た広告ネットワークが設置し、サイト訪問の記録を広告主などと共有することがあります。',
  'cookie.s4_title': '4. サードパーティCookie',
  'cookie.s4_p1': '当社のCookieに加え、サービスの利用統計の報告や、サービス上・経由での広告配信などのため、各種サードパーティのCookieを使用することがあります。',
  'cookie.s4_ga': 'Google Analytics',
  'cookie.s4_ga_p1': '当社は、お客様のサイト利用状況を把握するためにGoogle Analyticsを使用しています。Google AnalyticsはCookieにより、訪問頻度、閲覧ページ、流入元サイトなどの情報を収集します。当社はこの情報をサイト改善の目的でのみ使用します。',
  'cookie.s4_ga_link': 'Googleによるデータの取扱いの詳細は、Googleのプライバシーと利用規約をご覧ください。',
  'cookie.s4_partners': '広告パートナー',
  'cookie.s4_partners_p': '当社は、お客様が当社ウェブサイトを訪問した際に広告を配信するため、第三者広告会社と提携しています。これらの会社は、氏名・住所・メール・電話番号を除く、当サイトおよび他サイトへの訪問情報を用いて、お客様の興味に合った商品・サービスの広告を提供することがあります。',
  'cookie.s5_title': '5. Cookieの管理',
  'cookie.s5_p1': 'お客様はCookieの受け入れまたは拒否を選択する権利があります。Cookie同意管理で設定するか、ブラウザの設定でCookieの受け入れ・拒否を変更できます。Cookieを拒否した場合でも当社サイトは利用できますが、一部の機能や領域へのアクセスが制限される場合があります。',
  'cookie.s5_p2': 'ブラウザごとにCookie拒否の方法が異なるため、各ブラウザのヘルプメニューをご確認ください。主なブラウザのCookie管理リンクは以下のとおりです。',
  'cookie.s5_p3': 'すべてのウェブサイトでGoogle Analyticsによるトラッキングを無効にするには、',
  'cookie.s6_title': '6. お問い合わせ',
  'cookie.s6_intro': 'Cookieその他の技術の使用についてご質問がある場合は、以下までご連絡ください：',
  'cookie.s6_company': '上京プロパティ株式会社',
  'cookie.s6_email': 'メール：',
  'cookie.s6_address': '住所：',
  'cookie.s6_website': 'ウェブサイト：',
  'cookie.s7_title': '7. 本政策の変更',
  'cookie.s7_p1': '当社は、使用するCookieの変更やその他の運営・法的・規制上の理由により、本Cookie政策を随時更新することがあります。Cookieおよび関連技術の利用について最新の情報をご確認いただくため、定期的に本政策をご覧ください。',
  'cookie.s7_p2': '本Cookie政策の冒頭の日付は、最終更新日を示しています。',

  // Privacy Policy
  'privacy.company': '上京プロパティ株式会社',
  'privacy.title': 'プライバシー',
  'privacy.effective': '施行日：2026年3月4日',
  'privacy.last_updated': '最終更新：2026年3月4日',
  'privacy.s1_title': '1. はじめに',
  'privacy.s1_p1': '上京プロパティ株式会社（「当社」）は、日本国内の不動産を検索・閲覧いただくためのウェブサイトを運営しています。当社は、お客様の個人情報とプライバシーを適切に保護します。本ポリシーは、本サイトのご利用にあたり、当社がどのように個人情報を取得・利用・開示し、保護するかを定めます。',
  'privacy.s1_p2': '本ポリシーにご同意いただけない場合は、本サイトをご利用にならないでください。',
  'privacy.s2_title': '2. 取得する情報',
  'privacy.s2_p1': '当社は、お客様を識別し、またはお客様に関連しうる情報（「個人情報」）を取得する場合があります。主に次の区分があります。',
  'privacy.s2_h1': 'A. お客様が提供する情報',
  'privacy.s2_p2': 'お問い合わせ、会員登録、資料請求等の際に、お客様からご提供いただく情報です。内容はやりとりの内容により異なりますが、例えば次のとおりです。',
  'privacy.s2_li1': '氏名：お客様の識別、賃借人・購入希望者としての対応のため。',
  'privacy.s2_li2': 'メールアドレス：お問い合わせへの回答、物件情報のご案内、アカウント管理のため。',
  'privacy.s2_h2': 'B. 自動的に取得する情報',
  'privacy.s2_p3': '本サイトの閲覧・利用時に、端末情報や利用状況等が自動取得される場合があります。単体では特定の個人を識別しない情報（IPアドレス、ブラウザ種別、参照元URL、アクセス日時等）が含まれることがあります。',
  'privacy.s3_title': '3. 利用目的',
  'privacy.s3_p1': '当社は、法令に基づく場合、契約の履行、お客様の同意、正当な事業運営のために、取得した個人情報を次の目的で利用します。',
  'privacy.s3_li1': '物件検索・マッチング：お客様の条件に沿った物件情報の提供。',
  'privacy.s3_li2': '連絡：お問い合わせへの回答、サービスに関する重要なお知らせ、規約・ポリシーの変更等の通知。',
  'privacy.s3_li3': '品質向上：アクセス解析等によりサイトやサービスを改善するため。',
  'privacy.s3_li4': 'マーケティング：お客様の同意がある場合に、新着物件等のご案内メールを送付する場合があります。配信停止はいつでも可能です。',
  'privacy.s4_title': '4. Cookie等の技術',
  'privacy.s4_p1': '当社は、Cookieおよび類似の技術を使用する場合があります。詳細は当社のCookieポリシーをご覧ください。',
  'privacy.s4_ga': 'Google Analytics',
  'privacy.s4_ga_p': '当社は、サイトの利用状況の分析にGoogle Analyticsを利用する場合があります。取得情報は集計・匿名化されることがあります。オプトアウト用のブラウザアドオンもご利用いただけます。',
  'privacy.s4_adv': '広告用Cookie',
  'privacy.s4_adv_p': '第三者の広告配信事業者が、Cookie等を用いて興味関心に応じた広告を表示する場合があります。',
  'privacy.s4_p2': 'ブラウザの設定でCookieを無効化できますが、一部機能が利用できなくなる場合があります。',
  'privacy.s5_title': '5. 第三者への提供',
  'privacy.s5_p1': '当社は、法令に基づく場合、お客様の同意がある場合、または業務委託先への必要な範囲での提供等、適法な根拠に基づき個人情報を共有・提供することがあります。',
  'privacy.s5_li1': '物件オーナー・仲介業者：お客様が問い合わせた物件の取引手続きのため、氏名・連絡先等を提供することがあります。',
  'privacy.s5_li2': '委託先：ホスティング、メール送信、データ分析等の業務を委託する場合、必要な範囲で個人情報を預託することがあります。',
  'privacy.s5_li3': '法令・当局：法令に基づく開示命令等がある場合に開示することがあります。',
  'privacy.s6_title': '6. 保管期間',
  'privacy.s6_p1': '当社は、利用目的の達成に必要な期間、または法令で定められた保存期間の範囲内で個人情報を保管し、不要となった場合は削除または匿名化します。',
  'privacy.s7_title': '7. お客様の権利（日本法）',
  'privacy.s7_p1': '個人情報の保護に関する法律（APPI）に基づき、お客様は保有個人データについて次の権利を有する場合があります。',
  'privacy.s7_li1': '開示請求：当社が保有する個人データの開示を請求する権利。',
  'privacy.s7_li2': '訂正等：内容が事実でない場合の訂正・追加・削除を請求する権利。',
  'privacy.s7_li3': '利用停止等：不当な取扱いがある場合の利用停止・消去を請求する権利。',
  'privacy.s7_li4': '第三者提供の停止：法令に違反する第三者提供の停止を請求する権利。',
  'privacy.s7_p2': 'これらの請求は、末尾のお問い合わせ窓口から可能です。法令に従い対応します。',
  'privacy.s8_title': '8. セキュリティ',
  'privacy.s8_p1': '当社は、個人情報の漏えい、滅失、毀損等を防ぐため、適切な技術的・組織的安全管理措置を講じます。インターネット上の送信は完全な安全性を保証できないため、ご利用はお客様の責任において行ってください。',
  'privacy.s9_title': 'お子様のプライバシー',
  'privacy.s9_p1': '本サービスは18歳未満の方を対象としていません。18歳未満の方から意図的に個人情報を収集したり、マーケティングを行うことはありません。本サイトをご利用になる場合、18歳以上であること、または保護者の同意のもと未成年の利用に同意することを表明したものとします。',
  'privacy.s10_title': '10. 本ポリシーの変更',
  'privacy.s10_p1': '当社は、必要に応じて本ポリシーを変更することがあります。変更後の内容は本サイトに掲載した時点から効力を生じます。定期的に本ポリシーをご確認ください。',
  'privacy.s11_title': '11. お問い合わせ',
  'privacy.s11_p1': '本ポリシーに関するご質問、または日本法に基づく権利行使等は、次の窓口までご連絡ください。',
  'privacy.s11_address': '住所：',
  'privacy.s11_email': 'メール：',
  'privacy.s12_title': '12. 準拠法',
  'privacy.s12_p1': '本ポリシーおよび関連する紛争は、日本法（個人情報の保護に関する法律（APPI）を含む）に準拠し、東京地方裁判所または東京簡易裁判所を第一審の専属的合意管轄裁判所とします。',

  // Terms of Service
  'terms.company': '上京プロパティ株式会社',
  'terms.title': '規約',
  'terms.last_updated': '最終更新：2026年3月4日',
  'terms.s1_title': '1. 規約への同意',
  'terms.s1_p1': '本利用規約（「本規約」）は、上京プロパティ株式会社（「当社」）が提供する不動産検索ウェブサイトおよび関連サービス（「本サービス」）の利用条件を定めます。',
  'terms.s1_p2': '本サービスにアクセス、閲覧、または利用した時点で、ユーザーは本規約に同意したものとみなします。同意いただけない場合は、本サービスをご利用にならないでください。',
  'terms.s2_title': '2. サービス内容',
  'terms.s2_p1': '本サービスは、日本国内の不動産を検索・閲覧するための情報提供プラットフォームです。',
  'terms.s2_p2': '当社は情報提供および仲介に関するサポートを行う場合がありますが、掲載物件の所有権を有するものではありません（別途明示がある場合を除きます）。',
  'terms.s3_title': '3. 利用資格',
  'terms.s3_p1': '本サービスは、日本に居住する方または日本への移住を検討している方を主な対象とします。利用にあたり、次のことを表明・保証するものとします。',
  'terms.s3_li1': '18歳以上であること、または保護者の同意を得ていること。',
  'terms.s3_li2': '日本法上、有効な契約を締結する能力を有すること。',
  'terms.s3_li3': '当社に提供する情報が真実かつ正確であること。',
  'terms.s4_title': '4. アカウント',
  'terms.s4_p1': '物件問い合わせ等の機能に一部、アカウント登録が必要な場合があります。',
  'terms.s4_h1': '4.1 登録情報',
  'terms.s4_p2': '登録時は、正確かつ最新の情報（氏名・メール等）を提供し、ログイン情報の管理は自己責任で行ってください。',
  'terms.s4_h2': '4.2 セキュリティ',
  'terms.s4_p3': 'アカウント上で行われた行為は、ユーザー本人の責任とします。不正利用の疑いがある場合は直ちに当社にご連絡ください。',
  'terms.s5_title': '5. 禁止事項',
  'terms.s5_p1': 'ユーザーは、本サービスの利用にあたり、次の行為を行ってはなりません。',
  'terms.s5_li1': '法令または第三者の権利に違反する行為。',
  'terms.s5_li2': '詐欺、違法、または不当な目的での利用。',
  'terms.s5_li3': '虚偽、誤解を招く、不正確な情報の送信。',
  'terms.s5_li4': '当社または第三者のシステム、ネットワークへの不正アクセス、妨害、解析。',
  'terms.s5_li5': '当社の許可なく、本サービスの内容をスクレイピング等により複製・収集・再配布する行為。',
  'terms.s5_li6': 'スパム、未承諾の勧誘、連鎖メール等の送信。',
  'terms.s5_li7': '第三者のなりすまし、または関係性の虚偽表示。',
  'terms.s6_title': '6. 知的財産権',
  'terms.s6_p1': '本サービスに掲載される文章、画像、ロゴ、ソフトウェア等に関する著作権その他の権利は、当社または正当な権利者に帰属します。',
  'terms.s6_p2': 'ユーザーには、本規約の範囲内での閲覧・利用に限り、非独占的かつ譲渡不能な利用を許諾します。無断での複製、改変、配布、二次利用は禁止します。',
  'terms.s7_title': '7. 免責事項',
  'terms.s7_p1': '本サービスは「現状有姿」および「提供可能な範囲」で提供されます。当社は、法令で認められる範囲で、商品性、特定目的適合性、非侵害性等の黙示保証を含め、一切の保証をしません。',
  'terms.s7_p2': '当社は、本サービスがユーザーの要求を満たすこと、中断・エラーがないこと、結果の正確性、第三者コンテンツの正確性等について保証しません。',
  'terms.s8_title': '8. 責任の制限',
  'terms.s8_p1': '法令が許す最大限の範囲で、当社は本サービスの利用に関連して生じた間接損害、特別損害、結果的損害、逸失利益等について責任を負いません。',
  'terms.s8_p2': '当社は、掲載情報の誤り、本サービスの利用による身体・財産の損害、不正アクセス等についても、当社に故意または重過失がある場合を除き責任を負いません。',
  'terms.s9_title': '9. 準拠法と管轄',
  'terms.s9_p1': '本規約は日本法に準拠します。本規約に関する紛争は、東京地方裁判所または東京簡易裁判所を第一審の専属的合意管轄裁判所とします。',
  'terms.s10_title': '10. 規約の変更',
  'terms.s10_p1': '当社は、独自の裁量により、本規約をいつでも変更または置き換える権利を留保します。変更が実質的なものである場合、新規約の発効の少なくとも30日前までに通知するよう努めます。実質的な変更かどうかは当社が判断します。',
  'terms.s10_p2': '変更後に本サービスを継続利用された場合、変更後の規約に同意したものとみなします。同意いただけない場合は、利用を中止してください。',
  'terms.s11_title': '11. お問い合わせ',
  'terms.s11_p1': '本規約に関するお問い合わせは、次の窓口までご連絡ください。',
  'terms.s11_email': 'メール：',
  'terms.s11_address': '住所：',
  'terms.copyright': '© 2026 TK LLC. All rights reserved.'
};

export function t(key: string): string {
  const v = UI_STRINGS[key];
  if (v === undefined) {
    if (import.meta.env.DEV) console.warn(`UI string not found: ${key}`);
    return key;
  }
  return v;
}

export type AppLanguage = 'ja';

export interface LanguageContextValue {
  language: AppLanguage;
  t: typeof t;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const value = useMemo<LanguageContextValue>(
    () => ({
      language: 'ja',
      t,
    }),
    []
  );
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}