-- 物件のタイトル・住所の翻訳キャッシュ（DeepL 結果を保存して API 呼び出しを削減）
CREATE TABLE IF NOT EXISTS public.property_translations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id bigint NOT NULL,
  field text NOT NULL CHECK (field IN ('title', 'address')),
  lang text NOT NULL DEFAULT 'zh' CHECK (lang = 'zh'),
  value text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (property_id, field, lang)
);

CREATE INDEX IF NOT EXISTS property_translations_property_id_idx
  ON public.property_translations (property_id);

COMMENT ON TABLE public.property_translations IS 'Cached DeepL translations for property title/address (JA→ZH)';
